midudev/la-velada-web-oficial

.gitignore, README.DEV.md
Add readme for devs, contains explanation of projects
=> 🎉 init(README for devs): Readme For devs

README.md
=> Add Stack and Contributors in Readme.md

src/sections/PrincipalDate.astro
En esta PR he usado la maravilla de Intl.DateTimeFormat para obtener la zona horaria del usuario y mostrar la fecha y hora que corresponda.
=> feat: Show datetime according to the user country

src/sections/Footer.astro, src/sections/PrincipalDate.astro
Agregar el valor al atributo `aria-hidden`
=> Fix aria-hidden value

src/sections/Info.astro
Arreglando el Grid en la parte de las informaciones.
**ANTES**
**DESPUES**
=>  Fixing grid columns in info.astro

src/components/Date.astro, src/sections/Countdown.astro
Create a separate component for time html tags.
=> Create time component

src/sections/Info.astro
=> Quitar width innecesario y agregar text balance

.gitignore
=> Update .gitignore | Hiding lock files

src/components/Date.astro, src/sections/Countdown.astro, src/sections/Footer.astro, src/sections/Hero.astro, src/sections/Info.astro, src/sections/PrincipalDate.astro
Cambiar todos los conjutos de clases de Tailwind "justify-center items-center" a "place-items-center"
=> Place items center

CONTRIBUTING.md, README.md
PR Creada para agregar archivo CONTRIBUTING.md.
Se modificó en archivo README.md con el fin de indicar los contribuyentes, y como se podría contribuir a este proyecto
=> Agregar CONTRIBUTING.md

src/sections/PrincipalDate.astro
Quizás es ponerse demasiado tiquismiquis, pero creo que ya que todo el código está en inglés, los comentarios también deberían de estarlo 😄
=> fix: change spanish comment to english

src/consts/event-date.ts, src/sections/Countdown.astro, src/sections/PrincipalDate.astro
To avoid multiple sources of truth
=> Separate Event Timestamp to its own file in "consts"

src/layouts/Layout.astro, src/pages/index.astro
Added a 3D efect to konami rotation.  
Also used event.key instead of event.keyCode at 'keydown' to detect konami to add support to all browsers an OS.
=> Change konami functionality

src/layouts/Layout.astro
Mientras Tanto, no sé si ya exista alguna imagen para el OG Image así que no deje así como para por lo menos darle atención al OG XD
=> Basic minimum OG added

src/sections/Info.astro
Agregado de artículo "femenino" en sección de Información.
=> [FIX] - Agregado de artículo femenino en sección Info.

src/layouts/Layout.astro
=> :art: Beautify the scroll bar

src/sections/Footer.astro
Fix de este warning encontrado en el Lighthouse
=> fix: Set dimensions to icons

src/sections/Countdown.astro
Solo cambie la posición del texto en la section del contador me parece que se ve un poco mejor así:
Before:
After:
=> Change position text

src/layouts/Layout.astro
=> 📲 Fixed responsive svg

src/layouts/Layout.astro
This PR fix #95.
**Before:**
https://github.com/midudev/la-velada-web-oficial/assets/38303370/c635e957-bc5f-48e4-bad9-1a20267af6dc
**After:**
https://github.com/midudev/la-velada-web-oficial/assets/38303370/93145cb2-8453-46c7-a6b6-501007ac4b3b
=> fix viewport shrinking when alternate darkmode-lightmode

src/layouts/Layout.astro
alt attribute is added for the image of lights that are part of the background
=> add: alt attribute is added for the image of lights 

README.md
Mi propuesta es agregar un botón para iniciar el proyecto desde stackblitz, de esta manera cualquier persona con una cuenta de github va a poder iniciar a contribuir al proyecto facilmente y sin tener que instalar un ambiente de desarrollo en su compu.
- Se pretende acelerar el inicio de contribución de las personas que deseen hacerlo en el proyecto.
1. Agregar la posibilidad de crear un fork del proyecto en un ambiente creado dentro de stackblitz.
El principal impacto es reducir la friccion al querer iniciar a colaborar en el proyecto, reduciendo al mínimo el tiempo de configuración de ambiente de desarrollo.
=> [Cambio][Docs] Iniciar proyecto desde Stackblitz 

.vscode/settings.json
se configuro el archivo setting de vscode, se agrego la configuracion de format on save, para reducir los commits de formateo
#126
=> chore(vscode): add format on save setting

src/layouts/Layout.astro
Mejoro el contenido del meta description para un mejor SEO.
- Se ha cambiado el contenido del meta description quedando finalmente de la siguiente manera: "Web oficial de La Velada IV(4), evento de boxeo entre streamers y creadores de contenido, organizado por Ibai Llanos"
=> Mejoro el contenido del meta description

src/sections/Countdown.astro
Para pantallas pequeñas, se especifica un width máximo en el texto "PARA EL EVENTO DE PRESENTACIÓN FALTAN" con la finalidad de darle un diseño similar al del resto del diseño
En pantallas pequeñas, el texto "PARA EL EVENTO DE PRESENTACIÓN FALTAN" se extendía por toda la pantalla. El resto de elemento tienen un width restringido
1. Se especifica un width máximo en el texto "PARA EL EVENTO DE PRESENTACIÓN FALTAN"
2. Se coloca el width máximo por defecto en el breakpoint `sm:` 
| Antes | Después |
|---------|--------------|
| ![www lavelada dev_](https://github.com/midudev/la-velada-web-oficial/assets/70046023/1f2a6ede-350b-49d8-b45b-b79201bff939)  | ![localhost_4321_ (1)](https://github.com/midudev/la-velada-web-oficial/assets/70046023/ceeacab3-1b70-446c-b76b-bd4a2a5706e9)  |
1. Mejora en …
=> fix: make text "PARA EL EVENTO DE PRESENTACIÓN FALTAN" shrik on smaller screens

src/layouts/Layout.astro
Ya que los background `concrete` y `concrete-dark` se reemplazaron por el efecto de humo en Three.js, pero se seguían importando desde CSS, esto causaba un error en consola
Un error en consola no afecta mucho pero mejor prevenirlo :)
1. Se eliminaron las variables CSS donde se importaban los backgrounds
| Antes | Despues |
|---------|--------------|
| ![Screenshot_2024-02-28_16-40-11](https://github.com/midudev/la-velada-web-oficial/assets/70046023/1258b193-9f46-433b-88ed-e9a7e2178caa) | ![Screenshot_2024-02-28_16-45-07](https://github.com/midudev/la-velada-web-oficial/assets/70046023/0435b83f-ab87-4114-98a0-2688fea3a94b) |
1. Se elimina la request innecesaria para solicitar dichos backgrounds, que ni existen ni son necesarios
=> fix: remove useless background imports

src/components/TwitchLogo.astro
Se cambió la animación de los strokes, ahora usan `animation-timeline: scroll()` 
Al momento de scrollear los diferentes strokes del SVG de TwitchLogo.astro transicionaban mostrando colores diferentes (pero similares).
1. Verificar que el navegador soporte  `animation-timeline: scroll()` para aplicar las reglas, usando `@supports` de CSS.
2. Aplicar la regla de  `animation-timeline: scroll()` para los strokes del svg.
3. Cambiar los keyframes % de transición para que funcione en mobile y escritorio.
Basado en **caniuse.com** `view()` y `scroll()` poseen exactamente el mismo soporte en todos los navegadores, solo existiría algún problema si algún navegador soporta una de las dos. 
Parece que -por ahora- estas reglas de CSS son soportadas solamente por los navegadores basados en Chromium.
- …
=> Consistencia en color de logo twitch al scrollear

src/components/SmokeBackground.astro
Se soluciona el parpadeo del smoke cuando se cambia el tamaño del browser o la ventana, como se describe en #181 
fixes #181 
1. Se actualiza y dibujan las particulas nuevamente en el evento `resize`
https://github.com/midudev/la-velada-web-oficial/assets/70046023/83701204-2cba-48af-b4c1-8be456adc7db
1. Los usuarios podrán redimencionar tanto el browser como el window sin problemas visuales evidentes
2. El performance no debería verse afectado pues la animación periódica (`requestAnimationFrame`) se pausa (y luego se reanuda) mientras se actualiza el efecto. El pausado no afecta la visualización de la animación, se hace por prevención de degradar el performance
**Posible improvement**: Usar [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) para tener aún …
=> fix: smoke flickering on resize

README.md
He actualizado las imágenes que aparecían en el README, ya que el diseño ha cambiado un poco.
No era necesariamente un problema, pero sí que consideraba que el README debe estar lo más actualizado posible ✌🏽😊
🟢 Actualización de la imagen principal del README, se nota ligeramente el efecto de humo.
🟢 Actualización de la imagen de los móviles, donde aparece el un ejemplo de cómo se verá la página en esa versión.
🟢 Actualización de la imagen vista desde el ordena, se nota también ligeramente el efecto de humo que se le ha agregado recientemente.
ANTES:
DESPUÉS:
- [✅] He actualizado la documentación, si corresponde.
Con las imágenes tanto en la vista móvil como en la vista de ordenador, he contado con la colaboración de una amiga excepcionalmente talentosa: María Rodríguez 🌟, una destacada …
=> Update images README

src/components/Action.astro, src/components/CalendarButton.astro, src/sections/PrincipalDate.astro
Nuevo componente Action con los estilos de Agregar al calendario y Comprar entradas
El nuevo componente permite reutilizar los estilos en cualquier etiqueta HTML.
Se ha creado el componente Action, que ventajas tiene?:
- Un componente para cualquier etiqueta HTML => asi se reutilizan los estilos entre a, button...
- Estrictamente tipado es decir si le dices que es un `button` y le pasas el atributo `href` da error
```astro
---
import type { HTMLTag, Polymorphic } from "astro/types"
type Props<Tag extends HTMLTag> = Polymorphic<{ as: Tag }>
const { as: Tag, class: className, ...props } = Astro.props
---
<Tag class:list={["button-style", className]} {...props}><slot /></Tag>
```
```astro
// Como un a
<Action
as="a"
aria-disabled="true"
href="#"
target="_blank"
rel="noopener noreferrer" …
```
=> feat(components): Added Action

src/sections/Sponsors.astro
Los sponsors deberían tener esto para saber de dónde vienen, creo.
=> Remove `noreferrer` from sponsors links

src/sections/Footer.astro, src/sections/Sponsors.astro
Cree unas transiciones para que se vea un poco más fluido los hovers
Generé unos estilos para que en los sponsors el fondo cubra más todo el tag <a> y además en el footer los íconos de las redes sociales al hacer hover, tomen el color "primario" de la web
Dejo unos gifs:
- https://gyazo.com/ccf5baf94a09f27f23cbee340fd3aef6
- https://gyazo.com/7bfbdf3389159f7b594f44d7259a95f4
No afecta
=> smooth transitions

README.md
Updated README to the new website version
Updated README to the new website version
1. Updated mobile mockup
2. Updated desktop mockup
3. Changed title of "Capturas de pantalla" section
| Before | After |
| --- | --- |
|![image](https://github.com/midudev/la-velada-web-oficial/assets/67900366/ce2a68e2-e05b-46c2-9817-de91612822e6)|![image](https://github.com/midudev/la-velada-web-oficial/assets/67900366/69f84746-8f44-48b1-ab2b-95d45b0f5fab)|
=> 🪄 Updated README.md

src/sections/Sponsors.astro
Actualizada animacion del gradiente de sponsors para hacerla mas llamativa
Pequeño cambio en la animación de los sponsors
=> Smoother and more eye-catching gradiant animation

src/sections/Hero.astro
Actualiza la sección del Hero sustituyendo el elemento `<h2>` por un `anchor` que dirige el usuario al canal de Twitch de Ibai Llanos.
1. Sustituye el elemento `<h2>` por un `<a>`.
2. agrega una sutil animación `scale` + `underline` al hacer hover.
Ninguno
=> Update Hero section by adding the Twitch link

src/layouts/Layout.astro
Creado efecto de aurora implementado con solo css para usar en esta landing o en algun campo concreto de la web
https://github.com/midudev/la-velada-web-oficial/assets/85120579/391e358b-4a73-4c96-97bb-d6fd7bee6786
=> Created aurora effect on layout

src/sections/Error.astro
Esta PR introduce una mejora en la sección the Error usando el nuevo componente Action.
Mejora la mantenibilidad y legibilidad del código de la sección Error.
Reemplaza el css global con el nuevo componente Action
=> Use Action component in Error section

src/sections/Sponsors.astro
Ajuste la animación al pasar el mouse para una transición más suave y menos seca
Al parecer la transición actual en la sección de los Sponsors da un pequeño salto y es algo tardada, es por que falto animar la propiedad `height` ya que solo se anima la `opacity`. 
ANTES
DESPUES
- [ ✅] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ ✅] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
=> Fix hover transition

src/components/NoiseBackground.astro
Arreglar problemas de TypeScript
Arreglar problemas de TypeScript y mejorar la legibilidad del código.
Mejorar el tipado del código.
=> Fix TypeScript issues in NoiseBackground.astro file #255

src/components/ButtonUp.astro, src/components/NoiseBackground.astro, src/components/SmokeBackground.astro, src/sections/Hero.astro
Agrege 3 aria-labels, uno para un svg, y otros dos para canvas. Ademas de agregar un fondo para el h1 de "Presentación de la Velada del Año IV" para cumplir con las pautas WCAG.
Soluciona 4 problemas de accesibilidad en los navegadores: Firefox, LibreWolf.
- [✔️] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [✔️] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
Hay un cambio visual apenas perceptible en el fondo del h1. (Impacto muy bajo)
- Documentación: ![MDN Images](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#content_with_images_must_be_labeled), ![MDN Color …
=> fix: firefox accessibility issues

src/components/LiteYouTube.astro
Actualizados errores que producia el custom web component de LiteYoutube con el eslint a la hora de commitear cambios
En ciertas ocosiones producía problemas con los commits impidiéndolos
=> Actualizados errores que producia LiteYoutube con el eslint en los commits

.husky/pre-commit, src/sections/Hero.astro
Se corrige un error de estilo detectado por prettier.
Se modifica el pre-commit script para que de error cuando no cumple los estilos. De esta forma es imposible añadir un nuevo commit cuando no se cumplen los formatos de estilo.
Al realizar un commit se ejecutaba el pre-commit script para detectar posibles problemas de estilo.
Al detectarse, se corregía automáticamente, pero no se incluía en el actual commit que se estaba realizando.
De forma que si el usuario seguía realizando el commit sin añadirlo, el error seguía en el código fuente.
Corrección de estilos.
Modificación del pre-commit script.
=> styles: pre-commit should fail if lint or prettier fails

src/sections/PrincipalDate.astro
Pequeño efecto animado on hover de la localización del evento
=> Actualizado efecto hover de la localización

src/components/LiteYouTube.astro
Se actualiza el icono del reproductor para que se parezca mas al diseño original
Se actualiza el icono del reproductor para que se parezca mas al diseño original
=> Add: Actualizacion Icono para reproductor

package.json
=> fix: use correct pnpm hook to initialize husky as recommended in docs

src/components/KonamiCode.astro, src/components/LiteYouTube.astro, src/sections/PrincipalDate.astro, src/sections/SelectYourBoxer.astro, src/sections/Sponsors.astro, tsconfig.json
Se solucionaron algunos errores de TypeScript, ESLint y Prettier
=> Fix TS, lint and format errors

src/sections/Hero.astro, src/sections/PresentationVideo.astro
Aplicar user-select none a las imagenes de fondo de la pagina principal
A los idiotas como yo que se dedican a arrastrar el cursor por la pagina nos hará más felices
Añadir clase de tailwind
=> Setear user select none para imagenes de fondo

src/components/LiteYouTube.astro
He añadido hover al botón del reproductor de video. Al incorporar esta interactividad, proporcionamos retroalimentación instantánea a los usuarios, lo que facilita a comprender que el botón es interactivo y puedes reproducir el video.
https://github.com/midudev/la-velada-web-oficial/assets/112188399/1e5579fe-07a9-4ab7-9a72-956e251d2a6a
=> Interacción hover al reproductor de video

src/sections/Info.astro
Añadí el efecto de scale cuando se hace hover al icono de Twitch.
https://github.com/midudev/la-velada-web-oficial/assets/61954825/7a59bbf0-d592-45fa-9e1f-4bcf48a978f5
=> scale transition when hovering twitch icon

.vscode/settings.json
Anteriormente, el autocomplete de Tailwind no funcionaba en la directiva `class:list` de los componentes de Astro
1. Se modifica la configuración de vscode para permitir el autocomplete de Tailwind en las directivas `class:list`
1. Mejora en el DX
Husky me estuvo dando problemas para pushear los cambios ya que hay dos archivos que no están debidamente formateados (404.astro y Hero.astro). En mi local los formatee con `pnpm format` para poder subir este cambio. No subí los archivos formateados porque están fuera del scope de esta PR
=> chore: tailwind autocomplete on `class:list` Astro directive

src/components/LiteYouTube.astro
soy backend, pero creo que asi no esta tan seca la sección, pido perdón si ya lo vieron en esta sección, veo que le han metido mano fuerte estos dias.. suerte!
Creo que las sombras en el tono que propuse tienen relana  mas el recuadro a la vista que el borse seco con fondo en gradient
y transicion para hacer un mini zoom en el boton de play. Contaria como un Call to action
=> Sombray transiciones para el cuadro de video de presentacion

src/pages/404.astro, src/sections/Hero.astro, src/sections/SelectYourBoxer.astro
Realizar los cambios necesarios para que husky me permita realizar commits
Aunque el formato no es un problema en sí, es un poco molesto tener que borrar la carpeta husky para poder realizar commits y así colaborar con el proyecto, además los cambios a realizar eran muy pequeños
- Se abstrae a una constante la url "#" que todavía no se está utilizando pero si genera error con prettier
- Se arregla identación en 404.astro
- Se ordenan las clases en Hero.astro
=> Resolver errores de format

src/sections/Info.astro
Se unifica el efecto hover para el logo de twitch y el texto.
Se modifica el enlace para que ambos coincidan en https://www.twitch.tv/ibai.
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/57963142/53a16935-980d-4342-b430-39140d9c2b6e
Despues:
https://github.com/midudev/la-velada-web-oficial/assets/57963142/bde4b52c-918b-4a30-b109-bb432f5ef610
Mejora UX.
=> Actualización del efecto hover (twitch) en Info.astro

src/sections/PresentationVideo.astro
Arreglado fallo al cargar scrollbar duplicado -  inspired in #380 PR
Arreglado fallo al cargar scrollbar duplicado -  inspired in #380 PR
Hacer que la sección del video no sobrepase limites
No debería
Relacionado con #380 PR
=> [FIX] avoid duplicate scrollbar inspired in #380 PR

src/pages/index.astro, src/sections/Boxing.astro, src/sections/Info.astro
Se había ocultado la sección de Info (twitch.tv/ibai) sin querer. La he reactivado
=> [FIX] show info section

src/consts/sponsors.ts
En esta solicitud de extracción, he eliminado el interface `Sponsor` que se utilizaba para definir el tipo del array `SPONSORS`. Esta modificación permite aprovechar los tipos literales de TypeScript para mejorar la precisión del tipado en nuestro proyecto.
El uso del interface `Sponsor` resultaba en una inferencia de tipos como `string` y `number` para propiedades donde valores literales específicos ofrecen una mejor representación y seguridad de tipos. La eliminación del interface aborda este problema permitiendo una inferencia de tipo más precisa y descriptiva para cada patrocinador.
- Eliminación del interface `Sponsor`.
- Uso de `as const` para el array `SPONSORS` para inferir tipos literales para `id`, `name`, `url`, etc.
Estos cambios permiten que TypeScript infiera correctamente …
=> refactor(sponsor): 🔥 replace Sponsor interface with const assertion for precise typing

src/components/Date.astro
Se cambió la forma de gestionar el background en forma de paralelogramo.
Scroll horizontal en la página desde la resolución 768px hasta 1023px. #450 complementando la PR #458 
En lugar de manejar directamente el efecto de paralelogramo del fondo en el contenedor padre con la clase de Tailwind ```-skew-x-6```, se gestiona mediante el pseudoelemento ```::before``` del padre. A este pseudoelemento se le aplican los estilos del fondo y se utiliza la propiedad clip-path para lograr el efecto de paralelogramo. La clase ```-skew-x-6``` se aplica a los hijos que lo requieran. De esta manera, se evita que el contenedor se salga de los límites de la página al ser sesgado usando la clase ```-skew-x-6```.
antes:
despues:
=> fix: page horizontal scroll from resolution 768px to 1023px

src/components/ButtonUp.astro
El componente ButtonUp se ha mejorado y corregido para solucionar errores y optimizar su funcionamiento.
La variable `timeout` no se podía asignar correctamente al tipo de dato, se hizo una modificación en la función en general y se mejoro utilizando el método `requestAnimationFrame()`
Error y código anterior:
- **Actualización del método toggleScrollToTop:** Se reemplazó el uso de `parentElement` por el método `closest()` para obtener de manera más eficiente el elemento contenedor del botón de desplazamiento hacia arriba.
- Uso de constantes para código repetido.
- **Cambios en la función throttledScrollHandler:** Se implementó `requestAnimationFrame()` en vez de `setTimeout()` para optimizar la ejecución de la función `toggleScrollToTop` en respuesta al evento de desplazamiento …
=> Bug fixes and code improvements in Component ButtonUp

src/components/KonamiCode.astro, src/components/MiduCode.astro, src/layouts/Layout.astro
Se cambió la animación del konami code acorde a la propuesta de: #297 
https://github.com/midudev/la-velada-web-oficial/assets/50919956/a1637cfa-d78e-417d-be7d-f9829fdf0a52
[Issue 297](https://github.com/midudev/la-velada-web-oficial/issues/297)
Closes #297
=> Konami code animation: issue #297

src/components/Header.astro
Se me había pasado poner el absolute import en la anterior pr.
=> [FIX]  absolute import

src/consts/boxers.ts
Basicamente se ha añadido un nuevo campo en el tipo Boxer para poder calcular la edad en base a su fecha de nacimiento. 
Si uno de los boxeadores cumple años no hay que actualizar la edad.
Añadir el campo birthDate al tipo Boxer y crear una función que añade a todos los boxeadores un getter de age. Haciendo ese getter nos permite no tener que tocar nada más de código. Habría la opción de cambiar la página del boxeador y hacer ese cálculo en la misma view si es preferible.
=> Utilizar birthDate para calcular la edad

src/components/Header.astro
He agregado un indicador en escritorio y móvil que indique en que pagina estas en el menu
En el diseñó aparecía un indicador en el menu
Se ha agregado el indicador tanto al menu escritorio como al movil con su respectivo css y js.
Borre tambien el import del footer que no se estaba usando
Antes:
Después:
=> feat: Agregar indicador para actual page como en el diseño

src/components/Typography.astro
Hola! Estoy de vuelta y he realizado un pequeño cambio en el componente Typography que mejorará significativamente la accesibilidad de la página.
Empece atendiendo una parte de la directris 2.1 de la wcag
Guideline 2.1 Keyboard Accessible
[https://www.w3.org/TR/WCAG21/#keyboard-accessible](url)
Espero ir agregando mas PR que mejoren la experiencia de la pagina.
=> mejora para algunos componentes

src/components/Header.astro
Añadidos estilos al Header cuando se hace focus y al igual que cuando se hace hover.
Media query para las personas que tengan activada la reducción de animaciones.
1. Cambiar colores por variables de color `--color-accent`
Mejorar consistencia y aportar soporte a accesibilidad.
=> feat(Header): apply styles on focus and reduced animations

src/components/Header.astro
Solución de issue https://github.com/midudev/la-velada-web-oficial/issues/534
Cambios en el css para arreglar el menú en mobile.
Antes:
Despues:
=> Arreglar menú en mobile

src/components/HamburgerButton.astro
Solucionando problemas y mejoras en el código del componente `HamburgerButton`. Se han realizado ajustes para mejorar la legibilidad del código y evitar el uso de magic strings.
En mi Pull Request anterior había errores por temas de linter e importación pero ya están **solucionados**.
- **Mejora y solución en el código del componente `HamburgerButton`:** Se identificaron problemas relacionados con el linter debido al uso de backticks y a la importación de constantes. Se realizaron ajustes para mejorar la legibilidad del código y se evitó el uso de cadenas mágicas.
=> Code improvements in Component ButtonUp

src/components/Header.astro
=> [FIX] image lvda header src

src/components/KonamiCode.astro
Creadas flags para que no reproduzca en loop el midu/konamicode
Closes #530 
Mejor rendimiento
=> Flag konami code - Resolving Issue #530

src/sections/SelectYourBoxer.astro
Modificación del HTML para evitar elementos inesesarios en SelecYourBoxer resituando css con tailwind allí donde es necesario.
=> quit unnecessary HTML elements on SelecYourBoxer

src/components/TwitchLogo.astro
Le agregué una animación simple a los ojos del logo de Twitch
Le agregué una animación simple a los ojos del logo de Twitch
https://github.com/midudev/la-velada-web-oficial/assets/85404422/8608d328-db19-4d3c-9979-1cac9f731c6c
=> Add simple motion to the eyes Twitch logo

src/components/ColumnBoxers.astro, src/sections/SelectYourBoxer.astro
Responsive en Tablet de Seleccionar Boxeadores y el tamaño de los cards Boxeadores
**Antes**
**Después**
- [ x] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
=> Arreglando Responsive en Tablet para Vista de los Boxeadores

src/pages/boxers/[id].astro
Ajustar al diseño de la página de cada boxeador.
Modifica que en la información de su/s rival/es salga el/los nombre/s en Mayúsculas y no juntos.
1. Buscar los id de los rivales
2. Mostrar el nombre de los rivales
3. Unirlos con `y` si son dos.
Antes
Después
Ajustarse al diseño y mejorar la muestra de información.
=> feat([id]): adjusted to fit design

src/pages/boxers/[id].astro
Arreglando el responsive en modo Tablet de la página de Boxeadores
Se estaba rompiendo el diseño en la pantalla de Tablet
Cambio el lg:flex-row -> md:flex-row, para abarcar la resolución de tablet y agregué un gap-10 para hacer un poco de separación y que las estadísticas de los luchadores no choquen con el nombre del luchador en modo Tablet
**Antes**
**Después**
- [ x] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [ x ] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ x ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la …
=> Arreglando responsive pagina Boxer en Tablet

src/components/BoxerDetailInfo.astro, src/components/Velocimetro.astro, src/consts/combats.ts, src/pages/api/boxers/get-boxers-by-combat-id.json.ts, src/pages/api/combats/get-combat-by-boxer-id.json.ts, src/pages/api/forecasts/get-forecast-by-combat-id.json.ts, src/pages/boxers/[id].astro, src/sections/Forecasts.astro
Arreglar los errores y alertas señalados por el linter.
De 18 problemas a 2
Quedan 2 problemas debido a que hay un link sin href ya que aún no existe
Ya no se tendrán que hacer los commits con `--no-verify`, el "problema" del enlace no afecta
=> Linter fixes

src/components/ColumnBoxers.astro, src/consts/boxers.ts, src/sections/SelectYourBoxer.astro
…logica para demarcar los aliados con un filtro verde y enemigos con uno rojizo
Ahora se puede saber contra quienes es la pelea y si es una pelea en equipos se resalta al aliado del boxeador
No daba mucha informacion relevante la seleccion de boxeador
agregar filtros para que el usuario conozca los combates en la pantalla de seleccion
- [x ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione …
=> Marcar oponentes y aliados cuando se hace hover usando filtros

src/components/HamburgerButton.astro, src/components/Header.astro
No se estaba tirando el evento del hamburger component cuando había view transitions
=> [FIX] hamburger not dispatching event view transitions

src/consts/boxers.ts
Falta de Redes Sociales a luchador Karchez
add social links
=> Agregadas redes sociales para el boxeador Karchez

src/consts/boxers.ts
Agregados los Links del boxeador Skain
=> add skain social links

src/consts/boxers.ts
Agregados los links del luchador Pelicanger
=> add pelicanger links

src/consts/boxers.ts
Añadidos los links del luchador Unicornio
=> add unicornio links

src/consts/boxers.ts
https://instagram.com/mrangelovaldes
https://twitter.com/MrAngeloValdes
https://www.youtube.com/@misterfactoush
https://tiktok.com/@mrangelovaldes
=> Add Will socials media link

src/consts/boxers.ts
Las redes sociales de Aldo Geo
=> AldoGeo socialmedia

src/consts/boxers.ts
=> Sezar Blue Socialmedia

src/consts/boxers.ts
Añadidas las redes sociales de Roberto Cein
=> Roberto Cein social media

src/consts/boxers.ts
Agregué algunas frases y clips de Peldanyos que dijo en la presentación de la Velada. Son creo las mas relevantes que mencionó
=> Frases y clips de Peldanyos

src/consts/boxers.ts
Agregué algunas frases y clips relevantes de Pelicanger que dijo en la presentación de la Velada del año
=> Frases y clips de Pelicanger

src/consts/boxers.ts
Añadi 3 clips de la presentación sacados del video del canal oficial de Ibai.
clip 1
https://www.youtube.com/clip/UgkxgdKFyMCvRcN-fj-tuiF1i4KB2msHncZo
clip 2
https://youtube.com/clip/UgkxgTZz_h0N3COR9qQ6sRMmd_PSN_0CNFfJ?si=w5wRjWdKSjtiWnXx
clip 3
https://www.youtube.com/clip/UgkxHy3xXDVJdgv9BUaArwgIYrA_ae1M5FIX
=> Add Will clips presentation

src/components/BoxerBigImage.astro
he arreglado el drop shadow del select boxer para que cuadre
=> [FIX] drop shadow cropped

src/components/BoxerClips.astro
he arreglado el clip size para que se vea más ancho y también que se cargue el javascript del carousel de clips  en el page load de astro
=> [FIX] size clip and carousel astro page load

src/consts/boxers.ts
Añadí frases y clips de Folagor que mencionó en la presentación de la Velada
**En la PR están  las de Youtube, pero como Midu mencionó que estaría muy bueno hacerlo con una modal de Twitch haciendo un embed, dejé comentado las mismas frases pero con link a Twicth por si en algún momento se llegase a necesitar Twitch y no Youtube**
**Enlace donde Midu mencionó lo de Twitch:** https://www.twitch.tv/videos/2095407298?t=0h36m8s
=> Frases y clips de Folagor

src/consts/boxers.ts
Añadí algunas frases y clips que dijo Roberto Cein en la presentación de la Velada
=> Frases y clips de Roberto Cein

src/consts/boxers.ts
Añadí frases y clips de Aldo Geo que mencionó en la presentación de la Velada
=> Frases y clips de Aldo Geo

src/consts/boxers.ts
Añadi los clips relevantes de la presentación ( no hubo mucho salseo 😂 )
clip 1
https://www.youtube.com/clip/Ugkxjm_VBOO_hEVTcaT1iIn1wkqhdSgz0PEz
clip 2
https://www.youtube.com/clip/UgkxJxXzX5p5WQ-qnTCVSY_yHKLwN1mF_yRt
=> Add La Cobra clips presentation

src/consts/boxers.ts
Añadí algunas frases y clips de Karchez mencionadas en la presentación de la Velada
=> Frases y clips de Karchez

src/consts/boxers.ts
Algunas frases y clips sacados del cara a cara de Shelao y Viruzz en la presentación de la Velada
=> Frases y clips de Shelao

src/consts/boxers.ts
Algunas frases y clips mencionadas por Viruzz en el cara a cara contra Shelao en la presentación de la Velada
=> Frases y clips de Viruzz

src/consts/boxers.ts
Añadí algunas frases y clips de Agustín51 dichas en la presentación de la Velada del año
=> Frases y clips de Agustin51

src/consts/boxers.ts
Añadí unas frases y clips de Carreraaa mencionadas en el cara a cara de la presentación de la Velada
=> Frases y clips de Carreraaa

src/components/LiteYouTube.astro
Error al reproducir clips de YouTube.
Se agregó la funcionalidad para reproducir clips al componente LiteYouTube al pasarle como videoId parte de la URL del clip, al recortar y darle en la opción de Incorporar video como se muestra en la imagen.
<LiteYouTube videoId="ct0Hr6zYZGU?si=3UDv7SVmnHSXB3YM&amp;clip=UgkxtwjSORg57TZFqKsJBhUB1VqgYvL_W-cH&amp;clipt=EI_dygEY-cTLAQ" backgroundImage="/img/video-presentation-cover.webp" />
https://github.com/midudev/la-velada-web-oficial/assets/52842839/63f36cc7-193e-4848-91dc-1bfe8dde95e6
=> feat: Add Support for YouTube clips in the LiteYouTube component.

src/consts/boxers.ts
Algunas de las frases más relevantes de Guanyar durante la presentación de la Velada
=> Frases y clips de Guanyar

src/consts/boxers.ts
Algunas frases salseantes mencionadas por Alana en el cara a cara de la Velada
=> Frases y clips de Alana

src/consts/boxers.ts
Algunas de las frases más relevantes de Nissaxter durante la presentación de la Velada
=> Frases y clips de Nissaxter

src/consts/boxers.ts
Algunas de las frases más relevantes de Amablitz durante la presentación de la Velada
=> Frases y clips de Amablitz

src/consts/boxers.ts
The boxers are sorted in order to have a more readable display of the bouts.
- Order boxers
- Change some "rotate" options
=> Give a specific order to boxers

src/components/BoxerDetailInfo.astro
=> Remove unnecessary code in BoxerDetailInfo

src/components/Header.astro, src/components/Pronosticos/Vote.astro, src/pages/boxers/[id].astro, src/sections/PrincipalDate.astro, src/sections/SelectYourBoxer.astro
Despues de la pr https://github.com/midudev/la-velada-web-oficial/pull/704 al correr el comando `pnpm run format` se arrreglaron imports en multiples archivos.
=> Formatear proyecto

public/robots.txt
Agregar más información al archivo robots.txt como el sitemap y el host
El robots.txt no tenía casi información.
=> Agregar más información al archivo robots.txt

src/consts/boxers.ts
Unas frases dichas por Skain en la presentación de la Velada del año
=> Frases y clips de Skain

src/consts/boxers.ts
Añadí algunas frases y clips interesantes que mencionó Unicornio en la presentación de la Velada
=> Frases y clips de Unicornio

src/components/LiteYouTube.astro
Para evitar este error, pero manteniendo la accesibilidad, he cambiado el role por un aria-label
=> fix: remove att role button of lite youtube component

src/components/BoxerWorkout.astro, src/pages/boxers/[id].astro
Se ha agregado una modificación en el archivo `BoxerWorkout.astro`
El siguiente código se removió de `[id].astro` y se ha agregado en el archivo `BoxerWorkout.astro`
```
<section class="my-44">
<SectionTitle title="Entrenamiento" description="Preparación para el combate" />
</section>
```
No debería
=> refactor: BoxerWorkout file

src/sections/Info.astro
Añadir correctamente la transición al logo de Twitch en la seccion Info
La animación del logo de Twitch de la sección Info no funciona correctamente
Añadir la clase `duration-200`  al elemento para que el logo se anime correctamente.
**ANTES:**
[VIDEO_PR_ANTES.webm](https://github.com/midudev/la-velada-web-oficial/assets/67495604/a156ab02-7b2a-4d8f-b340-98674f46884c)
**DESPUES**
[VIDEO_PR_DESPUES.webm](https://github.com/midudev/la-velada-web-oficial/assets/67495604/63a37ec7-b354-40ad-b227-f30d883e12e4)
=> Fix Twitch logo animation

src/components/Pronosticos/Vote.astro
Se deja simetrica la lista como las imagenes.
Se propone solucion al "overlapping" de imagenes en el pronóstico en la versión mobile.
Las imagenes no tienen el mismo aspect ratio, lo que hacia que algunos combates fuesen más notorios que otros.
Se corrige el overlapping de las imagenes que se produce en mobile.
Se deja con un max-h-96 tanto para las imagenes como la lista queden con el mismo aspect-ratio.
Se tipifica que las actuales clases son para "md" y se añaden las de mobile.
NOTA: Se determino h-96 ya que 5 de los 6 combates en la lista median cerca de 380px.
Antes: ![CleanShot 2024-03-26 at 15 14 42@2x](https://github.com/midudev/la-velada-web-oficial/assets/5620412/bbb93b78-f9ff-4361-a0de-90c1e752bee5)
Después: ![CleanShot 2024-03-26 at 15 11 …
=> Se corrige la versión mobile de pronósticos.

src/sections/Countdown.astro
**_PR simple, pero siento que la página mejora un poco.
El título del Countdown está bien, pero creo que usando un Typography con la fuente atomic quedaría aún mejor_**
Aquí un antes y después:
**(Antes) : Sin Atomic**
**(Después): Con Atomic**
=> UI improvements to Countdown Title 

src/pages/combates/[id].astro
Cambios en el diseño de la sección Hero de cada combate, cambiando el tamaño del video y poniéndolo en el fondo.
Desde mi perspectiva y subjetividad no me gustaba mucho como quedaba el video en ese lugar así que probe ponerlo de fondo al tamaño de la pantalla.
Y ahora que hago esta pull request veo esta issue que también decía lo mismo 😅: https://github.com/midudev/la-velada-web-oficial/issues/750
😘
😁
🤗
=> Changes in the design of the Hero section of each combat.

src/components/Combates/CombatFeatureName.astro
Se arregla la url de los boxeadores en la tabla de información de los combates
=> Arreglar url de los boxeadores en la tabla de los combates

src/components/Pronosticos/Vote.astro, src/components/ui/Toast.astro
Modificación de estilos toast para adecuarse mejor al estilo general de la página
Lo cambios realizados han sido en el componente toast.astro y vote.astro
Se han eliminado los iconos usando emojis y se ha indicado al toast que use los iconos.
Bajos solamente modificación de CSS
- Código de referencia: https://github.com/midudev/la-velada-web-oficial/blob/44c70bffb4d5bda9bca97c7882238ca60683e1a8/src/components/Pronosticos/Vote.astro#L203C1-L229C9
=> Cambio de estilo del toast para que se integre mejor con la página

src/components/BoxerWorkout.astro, src/pages/boxers/[id].astro, src/sections/Combat.astro, src/sections/Info.astro, src/sections/SelectYourBoxer.astro
Se le quitaron los espacios innecesarios en mobile
closes #785
=> Removido el espacio innecesario en mobile

src/pages/combates/[id].astro
Usar la ya creada 'getCombatById'
uso de la función para evitar errores en diversos casos y no dejar código 'Vacío'
=> use getCombatById function

src/components/NoiseBackground.astro, src/components/NoiseBackgroundImage.astro, src/components/ui/Toast.astro, src/icons/horizontalScroll.astro, src/sections/Info.astro
Parte de solución, Issue https://github.com/midudev/la-velada-web-oficial/issues/798
Arreglados problemas de linter y formatter
=> fix(eslint, prettier): problems with linter and formatter

src/components/Header.astro
Añadida una animación de slide cuando cambias entre páginas en el header [SÓLO DESKTOP]
* Añadido `view-transition-name` a los pseudoelementos `::before` dentro de cada anchor en el header nav. 
https://github.com/midudev/la-velada-web-oficial/assets/34192442/08417b2c-ca2d-4043-b6e8-ed89bb6da4ba
=> Added slide animation to header nav

src/components/Combates/CombatFeatureName.astro
Evitar hover - unhover continuamente en la pagina de combates.
Se evita: 
https://github.com/midudev/la-velada-web-oficial/assets/106329576/b950a336-b1ee-4663-86c2-104e27864ed7
=> Fix: hover bug

src/components/BoxerSocialLink.astro, src/pages/boxers/[id].astro
@AlejandroSuero  hizo la PR #832 usando un renderizado condicional dependiendo si son 4 o 5 redes. Esta PR lo hace con flex
=> Fix issue #829 align social media but using flex

astro.config.ts
Actualmente las imágenes se encuentran dentro del `globPatterns` del workbox (PWA)
Esto hace que en la primera petición que haces de la página (incluso si estás en incógnito
o tienes la cache deshabilitada) se cargue absolutamente todas las imágenes del sitio
lo cuál no creo que tenga mucho sentido para esta aplicación web en particular.
Más aún teniendo en cuenta que ya se registró una política de cacheo para las imágenes:
https://github.com/midudev/la-velada-web-oficial/blob/88e67821ee0bbe3b4727fb9671da0c611cca2ad5/astro.config.ts#L47-L57
- Sacar las imágenes (junto con los svgs) del patrón global del workbox
> [!NOTE]
> No he podido replicar los cambios localmente debido a una configuración de middleware, pero hice
> esto antes con mi sitio web personal y funcionó como esperaba
Reducir …
=> fix: don't request all images with workbox

src/components/BoxerWorkout.astro, src/components/LiteYouTube.astro, src/consts/boxers.ts, src/sections/PresentationVideo.astro, src/types/Boxer.ts
Para intentar solucionar el issue [ fix #873 ], he modificado el componente liteYouTube y los archivos correspondientes para poder actualizar el título de manera dinámica.
Ahora muestra de manera dinámica el nombre del entrenamiento del boxeador.
Producción:
Localhost:
=> fix : alt text training vids #873

src/consts/boxers.ts
=> Update boxers.ts: Entrenamiento de El Mariana

src/consts/boxers.ts
Corrección del texto del vídeo de Guanyar.
=> fix: modify guanyar workout name

src/sections/SelectYourBoxer.astro
- Se mejora la experiencia de usuario para iOS
- Cambios en estilos del componente `ColumnBoxers.astro` para la parte mobile en iOS y Safari.
Antes
https://github.com/midudev/la-velada-web-oficial/assets/58793851/89ec0304-79bb-4dd5-97d0-639e6928c714
Después
https://github.com/midudev/la-velada-web-oficial/assets/58793851/9f5ba6f0-97bb-4232-b2a3-9269401ba479
=> Refactor carousel item mobile safari on scroll

README.md
He intentado solucionar la issue #901 
He especificado qué comando usar para levantar el proyecto con la db local. El script dev lanza el proyecto con la flag remote, forzando a usar Astro Studio, mientras que el script start permite que se cree una db local. Por otro lado, he añadido las instrucciones para poder iniciar sesión mediante twitch.
=> Añadidas instrucciones de instalación y ejecución

src/components/ColumnBoxers.astro
Para solucionar issue #909, he modificado el título.
Al hacer hover el título se adapta al boxeador/a.
closes #909 
Produ:
Local:
=> fix(#909) modify title picture hover

src/components/Pronosticos/Intro.astro
Este Pull Request introduce cambios en el manejo del botón de inicio de sesión en la versión móvil de la aplicación. Se ha corregido un problema por el cual el botón de inicio de sesión se quedaba en un estado “inhabilitado” después de que se cerraba la ventana de inicio de sesión.
El problema era que el botón de inicio de sesión se quedaba en un estado “inhabilitado” si se abría la ventana de inicio de sesión y luego se volvía atrás sin completar el inicio de sesión. Esto impedía que los usuarios pudieran intentar iniciar sesión de nuevo. Este problema solo ocurre en la versión móvil de la aplicación y no puede reproducirse utilizando las herramientas de desarrollador en un PC, ya que en ese entorno el botón funciona correctamente.
Se ha modificado el controlador del evento onclick del …
=> signin timeout

src/consts/boxers.ts
Edad y cumpleaños actualizados usando datos informados en un video de su canal.
Edad y cumpleaños. 
Actualización de las constantes del boxeador Sezar Blue.
- Momento del video donde comenta su cumpleaños https://youtu.be/QKUzwbauJt0?si=lS9beRYvfmY6zC7D&t=744 
- Documentación del proyecto: N/A
- Código de referencia: N/A
=> fix: sezar birthDate and age

README.md
Cambiado en el ReadMe una palabra que estaba en inglés por español
Una palabra del ReadMe estaba en inglés
Cambio la palabra de inglés a español
Antes
Despues
=> README | change english for spanish

src/components/SEO.astro
Open Graph (OG) meta tags in SEO component were corrected to ensure proper functioning on social networks and search engines.
The Open Graph meta tags were using the name attribute instead of property, which could have caused them not to display correctly in social media previews and search engine results.
The Open Graph meta tags in the SEO component were modified to use the property attribute instead of name, thereby ensuring their proper functioning.
Before:
After:
These changes should enhance the visibility and performance of the web application by ensuring that the Open Graph meta tags display correctly in social media previews and search engine results.
These changes were specifically made in the astro SEO component to ensure that the Open Graph meta tags are correctly generated in …
=> fix: incorrect format of open graph meta tags is fixed

src/components/CalendarButton.astro, src/components/TwitchLiveBox.astro
Fix bug caused by using dom/selector in inline scripts, which breaks `CalendarButton` and `TwitchLiveBox`components. Reverts some changes of https://github.com/midudev/la-velada-web-oficial/pull/934.
Browser raises the following error when trying to `import { $ } from "@/lib/dom-selector"`. This error breaks the `Agregar al calendario` button. This issue only appears in `is:inline` scripts. Regular `<script>` tags are not affected by this because are processed and bundled by Astro (see [this](https://docs.astro.build/en/guides/client-side-scripts/#script-processing)).
Using `querySelector()` fixes the issue. See the following demos before and after below.
Before:
https://github.com/midudev/la-velada-web-oficial/assets/345520/ae68394c-f10a-470f-8699-3a9510f07e35
After: …
=> Fix bug caused by using dom/selector in inline scripts, which breaks `CalendarButton` and `TwitchLiveBox` components

src/consts/boxers.ts
Añadido el peso de `El Mariana`.
Fixes #964
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/4fbcd5f7-0d10-4608-8c1c-db8cee20d16f
Depués:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/81fb1c20-8d67-4ed9-b441-72cdb84c0592
Mejorar la experiencia de usuario y mantener datos de los boxeadores.
=> fix(#964): añadido el peso de `El Mariana`

package.json
Cambios en [auth-astro](https://github.com/nowaythatworked/auth-astro) para evitar error 500.
@midudev
Fixes #963
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/b2258fe2-8a22-4a36-a624-900ba923559c
https://github.com/midudev/la-velada-web-oficial/assets/71392160/edbcef6b-d0e2-4ec6-9310-632576c63539
---
Después:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/566878fb-b412-4784-b72b-87775ec3fe83
Mejora de la experiencia del usuario y evitar errores 500.
=> fix(#963): cancelar la sesión ya no marca ERROR 500

LICENSE.md
midu made a mistake copy pasting the license file.
=> fixed license

CONTRIBUTING.md
added contributing file and changed instances of 'la velada del año 4' to 'la velada del año 5'
=> contributing md file

src/components/Footer.astro, src/components/Sponsors.astro, src/consts/sponsors.ts, src/layouts/Layout.astro, src/pages/index.astro, tsconfig.json
Se agrego la ruta absoluta con @ y se cambio las rutas relativas por la nueva
=> Agregando ruta absoluta con @

src/components/Sponsors.astro
Add alt for sponsors icons & aria-label for the section to specify the context of sponsors logos
=> accessibility: Sponsors

src/components/Footer.astro
=> social icons centered

src/components/Sponsors.astro, src/styles/global.css
using tailwind @theme variables
=> style: add color variable

src/components/Hero.astro
https://github.com/user-attachments/assets/eb2baec8-6d37-4633-9e43-897293e1591b
=> Animate hero text and image while hover

src/pages/luchador/[id].astro
small fix for firefox users:
current
updated:
=> fix: update boxer [id] for some browsers(firefox) compatibility

.github/pull_request_template.md
Added a new pull request template to improve contribution guidelines and standardize PR submissions. 
This change:
- Introduces a structured template for all pull requests
- Adds sections for change description and screenshots/videos
- Includes a checklist for type of changes (bug fix, feature, breaking change, docs)
- Makes it easier for contributors to provide relevant information
- Helps reviewers understand changes more effectively
N/A - This is a documentation change that adds a template file. No visual changes to showcase.
=> chore: add pull request template for better contribution guidelines

src/components/Hero.astro, src/styles/global.css
=> Fix scrollbar gutter and height viewport

.gitattributes
I created the `.gitattributes` file so that the `.astro` files are recognized as `Typescript` by GitHub Linguist.
Some PRs do not have the result for Typescript (e.g #1125)
<details open>
</details>
=> Create `.gitattributes` file

src/pages/luchador/[id].astro
Se cambiaron los tamaños de la imagen de los luchadores (ademas de agregarse el nombre)
Un diseño basico guiandose del hero, pero que sirve como inicio
=> fighter page fixed sizes

src/components/Header.astro
This PR adds a smooth transition effect to the underline of navigation items, enhancing the visual feedback and user experience.
https://github.com/user-attachments/assets/a50ff477-a0f6-4263-9bf8-c11754e90ea6
=> feat: Improved underline transition effect for navigation items

src/styles/global.css
Se han agregado unas pocas lineas de css para editar el scroll-bar y hacerlo mas amigable. La idea es una base para mejorarla posteriormente a medida que el proyecto se desarrolle.
Ventajas:
1. Facilmente editable.
2. Se puede añadir bordes y hover.
3. Los colores utilizados son del theme.
4. Se puede revertir los cambios facilmente.
SS de la barra por defecto del navegador,
Un cambio básico simple para hacerla mas amigable: 
https://github.com/user-attachments/assets/e0265bd6-2934-446c-8998-c12e3868ebb7
=> Feat: Cambio de color del scrolbar por defecto

src/pages/404.astro
Add Astro frontmatter to 404 page. It was previously removed in #1141
=> Fix: Add frontmatter to 404 page

src/pages/combates/[id].astro
En esta PR presento un nuevo formato para la página de información de los combates, con un diseño responsive y una leve animación para simbolizar el choque entre peleadores.
Puntos positivos:
- Diseño responsive en dispositivos pequeños, evitando el corte de imagen de la versión anterior.
- Capacidad de fácil mejora y edición.
- Solo afecta a la página /combates/id.astro.
- Solo utiliza una leve animación personalizada y clases de Tailwind.
- Espacio adaptable para los pronósticos; se pueden proponer diversos (ganador del combate, asalto estimado de victoria, victoria por puntos o K.O., etc.).
- Desactivando el scale puede ser agradable igualmente. 
Puntos menos favorables:
- Formato distinto entre las imágenes de los peleadores.
- Desventajas del recorte con clip-path.
- No se cuenta con …
=> Feat & Style: Editando concepto de pagina de información de combates

src/components/Header.astro
Se ha cambiado el logo del header por el favicon y reducido su tamaño para que quepa en el header.
Antes:
Después:
=> feat: update header logo size and source for improved branding

.prettierrc, .vscode/settings.json, scripts/generate-blur-placeholders.mjs, src/components/BoxerCard.astro, src/components/Footer.astro, src/components/SectionTitle.astro, src/components/SynthwaveText.astro, src/pages/404.astro, src/pages/combates/[id].astro, src/pages/luchador/[id].astro, src/sections/Countdown.astro, src/sections/Hero.astro, src/styles/global.css
It set the "text-transform" css propertie to uppercase in the "global.css" file and remove the " uppercase" and "lowercase" classes of all components
=> Fix: Set text-transform uppercase in global.css

src/components/BoxerCard.astro
Se ha modificado el componente BoxerCard.astro solamente para lograr este efecto, se uso el versus obtenido al hacer mouseenter en una card para hacer estos efectos se les agregaros las clases de tailwind para conseguir el efecto.
NOTA: hay algo que no pude, hacer lo cual es agrandar la tarjeta versus, debido a que si le pongo el mismo scale-110 al hacer hover en la tarjeta que se está haciendo hover, por alguna razon se ve mas grande que la otra, asi que no le coloque el "scale-110" a la cardVersus.
OTRA NOTA: Hola midu como estas, oye estoy haciendo una base de datos en mySql, donde me recomiendas alojar la base de datos?
ANTES: 
https://github.com/user-attachments/assets/1ab1be43-a8dc-4400-af46-8f5fa30fba08
DESPUES:
https://github.com/user-attachments/assets/490421fa-2778-453e-9ff4-4d0d …
=> feature/ addAnimations .Mejora la interacción de tarjetas de boxeadores versus al agregar mejores efectos visuales en el hero.

README.md
Cambie las imagenes del README.md ya que estaban desactualizadas (eran imagenes de la velada iv)
=> update README.md to replace logo and screenshot links with new assets

src/assets/svg/kick.svg, src/components/BoxerCard.astro, src/components/BoxerGallery.astro, src/components/BoxerSocialLink.astro, src/components/BoxerWorkout.astro, src/components/Sponsors.astro, src/pages/luchador/[id].astro
1. Se mejoro el diseño de los links de redes sociales en la pagina del boxeador, a continuacion muestro los cambios
2. Pequeños ajustes de diseño en la pagina de boxedor, para mejor responsive 
|Antes|Despues|
|---------|-----------
|![SCR-20250409-khow](https://github.com/user-attachments/assets/6c96a013-f83d-4178-8aa0-1cc2a16a8ce9)|![SCR-20250409-jzdc](https://github.com/user-attachments/assets/0ea26666-7b6c-4947-bbf0-c285911772ac)|
=> Se mejoro el diseño de los links de redes sociales

README.md
Update: Update README.md  file changing his name from 'Web ofical de la Velada IV' to 'Web ofical de la Velada V'
---
=> Update: Title change README.md

README.md
**change**
The text was changed from "La Velada IV es una competición" to "La Velada V es una competición"
=> Update: update README.md

src/consts/fighters.ts
- Updated the fighters cities to include their respective region/community (e.g., Mallorca → Mallorca, Islas Baleares).
- Corrected incorrect cities of fighters where necessary.
=> Updated fighters cities.

src/consts/fighters.ts
add comma in line 917
before
after
Se corrigió un error en el archivo Fighters.ts el cual botaba la página al ejecutar pnpm dev
=> fix bug in fighters.ts add comma

src/pages/combates/index.astro
adding fade-in animation when the combat appear in the viewport
https://github.com/user-attachments/assets/c059da1c-2cd1-4e77-af7a-a69991a9c781
=> adding view animation to combats

src/components/BoxerSocialLink.astro
=> Adjust the type import in BoxerSocialLink

src/pages/luchador/[id].astro
Not able to click on clips cards to active sidebar player
https://github.com/user-attachments/assets/7ec621ea-6bd0-4c97-8d72-aabb34058c9d
=> fix(luchador): drawer in `hidden` not triggering `onclick`

src/components/Boxers/ColumnBoxers.astro, src/components/Boxers/SelectYourBoxer.astro, src/lib/get-boxers.ts, src/sections/Hero.astro, src/utils/remove-mirrored-pairs.ts
Improved first iteration of the boxer selection in mobile
Before:
https://github.com/user-attachments/assets/9c153b09-99a2-4c8a-a728-47abc16a4733
After:
https://github.com/user-attachments/assets/028e79fa-5f70-442a-b412-4628e052ff7a
> [!note]
> Grefg vs Westcol was moved to appear first like in desktop
=> feat: update mobile boxer selector

src/sections/Header.astro
Centered brand logo within header.
Before;
After:
=> fix: adjust layout and positioning of logo to be centered and add glow for better contrast

src/sections/Entradas.astro
- Se añadió el efecto del botón de `Añade el evento al calendario!` al botón de `¡Entradas ya a la venta!`.
- Se ha corregido el scale que estaba implementado pero no se visualizaba.
- Se ha eliminado el parragraph para dejar solo el enlace.
https://github.com/user-attachments/assets/d1345988-b453-492b-afbd-7e8b653a4478
https://github.com/user-attachments/assets/ce6d86c1-a509-47ea-a514-17e7aebbc6c4
=> feat(Entradas): Add animation to Comprar las entradas button

README.md
Los bullet points de PNPM y NPM no se estaban mostrando correctamente
=> FIX: Arreglado error en bullet points

src/components/FAQ.astro
Changed FAQ colors to better fit the theme, updated sizes for better responsiveness and fixed SVG not having consistent size on mobile devices.
Antes:
Después:
=> feat: update faq theme and fix svg inconsistent size on mobile

README.md
Update README.md to redirect to the official website clicking in the main image
- [X ] Documentation update
=> Redirect to the official website
