src/sections/PrincipalDate.astro
En mi PR anterior solo usaba el TZ del usuario para la hora, pero no para el día. Esta PR lo corrige.
=> fix: Uso del TZ también para el día

src/layouts/Layout.astro
En conexiones lentas, el background podría tardar un poco en cargar. Con este commit se intenta solventar dicho problema cargando la imagen de antemano, antes que otros recursos
Antes: 
<video src='https://github-production-user-asset-6210df.s3.amazonaws.com/70046023/306803151-c10dab4f-fe4c-4e7d-ac03-8300a0410822.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20240221%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240221T232436Z&X-Amz-Expires=300&X-Amz-Signature=064b9339076a18a4a98756fc85b63a6f8d1958e3f4549252ca8c2f7772ee9931&X-Amz-SignedHeaders=host&actor_id=70046023&key_id=0&repo_id=761334150'></video>
Después:
=> fix: preload critical asset (background)

src/sections/PrincipalDate.astro
Se añade la link hacia la ubicación de Teatro Victoria en  google maps.
Imagen con efecto hover.
=> Añadir Link hacia la ubicación del Teatro Victoria 

src/sections/Info.astro
He solucionado un problema en la versión móvil (320px) donde un elemento desproporcionado ("padin") causaba un error en la interfaz de usuario, pegándola al lado izquierdo. Esta corrección permitirá que las personas con teléfonos móviles antiguos puedan ver correctamente la página de la velada 4.  ☺️
=> fix: Padding for 320px mobile S version

src/sections/Countdown.astro
Contexto para que se entienda que ahora la cuenta atras es para el evento de presentación, no por la Velada
=> Add temporal countdown context

src/sections/Info.astro
=> fix twitch icon color on dark mode

src/layouts/Layout.astro
light svg covers full width on mobile
before:
after:
=> now the light looks good on mobile

.prettierignore, .prettierrc.mjs, .vscode/extensions.json, .vscode/settings.json, astro.config.mjs, package.json, pnpm-lock.yaml
Se ha agregado la configuración para Prettier como formateador del código. Esto ayudará a mantener un estilo de código uniforme y legible en todo el proyecto.
=> Agregar configuración para Prettier como formateador de código

src/sections/Info.astro
Actualmente, cuando el scroll es pequeño y se hace `hover` sobre el link con texto "SÍGUELO EN DIRECTO TWITCH.TV/IBAI", el trozo "TWITCH.TV/IBAI" permanece con el color aplicado por el scroll timeline 
Antes:
<video src="https://github.com/midudev/la-velada-web-oficial/assets/70046023/4eb62999-a208-4481-8f05-3330d22b454f"></video>
Después:
<video src="https://github.com/midudev/la-velada-web-oficial/assets/70046023/9509bcbc-9053-478d-be02-16b87701f88f"></video>
=> fix: always show twitch color on link hover

src/layouts/Layout.astro
Ya arreglaron el problema anterior #84 pero aun hay un problema que me percate para este layout de "ipad mini" es el unico layout que me percate que tenia ese problema pero lo solucione solo agregando la clase al contenedor de la imagen "overflow-x-clip".
Ahora:
=> fix response on layout for ipad mini

src/components/CalendarButton.astro
En dispositivos con conexiones lentas (probar con 3G lento en las herramientas del desarrollador) el boton "Agregar al calendario" tarda un poco ya que por cada click se importa el JS y CSS para agregar al calendario.
Ahora la primera vez que se hace click en el boton aparece "Cargando..." en el texto momentaneamente, se carga y muestra el calendario. Las siguientes veces ya no es necesario cargar y lo muestra de inmediato
Agregue una variable en el script de CalendarButon.astro con el estado, y cuando el boton hace click, si no esta cargado lo carga, si ya esta cargado muestra el calendario de una vez, y si el usuario hace varias veces click si todavia esta cargando no hace nada, para no hacer mas descargas innecesarias 
https://github.com/midudev/la-velada-web-oficial/assets/56895143/cb5 …
=> [feat]: Optimizacion carga del calendario

README.md
La lista de los contribuidores por algún motivo no se muestra completa. Esta PR pretende solucionarlo.
Ahora se ve la lista completa de contribuidores.
Se removió el `&theme=flat` del URL de los contribuidores.
| Antes  | Ahora |
| ------------- | ------------- |
| ![image](https://github.com/midudev/la-velada-web-oficial/assets/56328053/2a88453c-97a1-4fe4-822a-f855a91be8ae) |  ![image](https://github.com/midudev/la-velada-web-oficial/assets/56328053/c22d9dc0-2f13-4cfa-b6ee-d3244bcbe10c) |
https://contrib.rocks/
=> Update contributors URL

src/icons/map-marker.astro, src/sections/PrincipalDate.astro
Añadí un icono de map-marker junto al texto del Teatro. Esto es porque la primera vez que usé la página no me di cuenta de que era clickeable ese texto ya que visualmente no tiene nada distintivo. Mantuve el estilo y colores del resto del diseño y creo que queda bastante bien para que se de a entender de que ese texto es un botón.
=> Add map marker

src/sections/Footer.astro
Es preferible utilizar el HTMLEntity `&copy;` en lugar de un codigo numerico para representar el icono de copyright en el footer. Puesto que, esto hace que sea mas legible y facil de entender, ademas de que tambien es compatible con todos los navegadores y editores de codigo.
cambiar el codigo numerico que representa el caracter de copyright, por un HTMLEntity `&copy;`
=> update copyright icon to html entity

src/sections/Info.astro
Añadí una transición al link de Twitch de Ibai y eliminé un bloque de script de Astro.  
Añadí la transición ya que al hacer hover sobre el link de twitch de Ibai hace el cambio de color bruscamente lo cual rompe con lo establecido en el resto de la página porque esto no ocurre con ningún otro link o componente.
Eliminé el bloque script de Astro porque no se estaba utilizando para nada.
https://github.com/midudev/la-velada-web-oficial/assets/137431919/7b15f44e-dcd1-4286-b63b-0c1efe6a9611
https://github.com/midudev/la-velada-web-oficial/assets/137431919/250cbdee-1540-4f7d-b482-4aca95467a0a
=> Add transition twitch ibai and remove unnecessary component script block 

src/components/CalendarButton.astro, src/components/ThemeToggle.astro, src/sections/Countdown.astro, src/sections/Footer.astro, src/sections/Info.astro, src/sections/PrincipalDate.astro
He agregado algunos aria-labels que faltaban y he mejorado la información de otros como por ejemplo para los links o botones que se abren en una nueva pestaña, siempre hay que avisar al usuario de que va a salir de la página en la que está navegando. 
He añadido además un poco de código Javascript en el archivo `ThemeToggle.astro` para que el screen reader pueda leerle al usuario el color theme actual y así pueda decidir mejor si quiere cambiarlo o no. 
Encontré un error en la cuenta atrás, el screen reader solo leía el primer texto correspondiente al día, y ahí acababa todo, no seguía leyendo el resto de la página, se "bloqueaba" ahí el lector. 
Para solucionarlo he agregado `role="timer"` al div que lo contiene, de esta manera el screen reader puede leer el texto de la cuenta atrás y …
=> Add: mejoras para la accesibilidad, sobretodo para los screen readers

src/components/SmokeBackground.astro
Algunos usuarios suelen tener las animaciones deshabilitadas, por lo que estaría genial respetar eso y prevenir usar Three.js en esos casos. Se ha agregado un `if` al inicio del código para evitar hacer el smoke animation si el usuario tiene las animaciones deshabilitadas.
Se lee la preferencia del usuario al inicio del script y se crean las animaciones solo si el usuario tiene no tiene el `prefers-reduced-motion` habilitado.
Aún puede mejorarse, por ejemplo, importar Three.js dinámicamente si el usuario tiene las animaciones activadas.
Otra mejora puede ser escuchar los cambios en el `prefers-reduced-motion` en tiempo real. Actualmente solo se actualiza al recargar la página.
Nota: En el _diff_ quizás sea difícil de ver los cambios que he agregado, esto es porque agregué un `if` al …
=> Prevent smoke animation if user has animations disabled

src/components/KonamiCode.astro, src/layouts/Layout.astro
Solucioné un problema con el código Konami, el fondo con humo se iba a la parte de arriba de la página durante la rotación.
- Se agregó un ID en la sección con contenido de la página para así hacerla accesible desde el componente del Konami
- Se cambió para usar comparaciónes estrictas en los IFs
- En vez de girar el body, se gira la sección con contenido para mantener el fondo fijo
=> Fix konami errors

src/components/Date.astro, src/sections/Countdown.astro
Se agrega una animación en la cuenta regresiva al cambiar un dígito.
En la versión anterior, el cambio de dígito en la cuenta regresiva es completamente estático, por lo tanto se agrega una pequeña animación de transición para que no sea tan brusco y se pueda apreciar.
- Se elimina el parámetro "time" del componente Date, ya que inicialmente es 0 y resulta innecesario.
- Se agregan 2 listas verticales de números del 0 al 9 en el componente Date, las cuales se utilizan para hacer la transición de dígitos usando la posición en Y relativa.
- Se modifican las constantes $days, $hours, $minutes y $seconds en la sección Countdown para poder abarcar los 2 dígitos de las mismas.
- Se agrega la función animateDigit en la sección Countdown para poder hacer la transición en Y del nuevo dígito, donde …
=> feat: Add Countdown animation

src/sections/Countdown.astro
Quitar el texto "Para el Evento de Presentación faltan" cuando termine el contador y cambiar el texto "¡La velada ha comenzado! 🎉" por "¡El evento de presentación ha empezado! 🎉"
=>  - Remove countdown text when event starts

src/components/TwitchLogo.astro
Safari no soporta el `animation-timeline`.
Se ha creado un fallback para que en Safari se vea la versión de color del logotipo de Twitch, en lugar de la versión a 1 tinta.
Can I Use del animation-timeline: [caniuse-animation-timeline](https://caniuse.com/?search=animation-timeline)
=> fix: animation-timeline Safari fallback

src/components/SmokeBackground.astro
Añadido aria-hidden="true" al elemento background de efecto de humo.
Agregué el aria-hidden="true" al div para que los screen readers no lean este div que es meramente decorativo
no afecta
- ✅ He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- ✅ He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- ✅ He actualizado la documentación, si corresponde.
No impacta negativamente
Utilizado el doc de mdn
- Documentación del proyecto: [[mdn](url)](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)
- Código de referencia: 
<button>
<span class="fa fa-tweet" aria-hidden="true"></span>
<span class="label"> Tweet </span>
</button>
=> aria-hidden="true" for accessibility

src/components/CalendarButton.astro, src/sections/PrincipalDate.astro
Se ha eliminado CSS duplicado y clases innecesarias de Tailwind en `src\components\CalendarButton.astro`. Por consecuente, se han actualizado los selectores en el CSS de `src\sections\PrincipalDate.astro`.
Además, se ha incluido una transición de 150ms en el _scale_ de los botones (_**Entradas Agotadas**_ y _**Agregar al calendario**_) al momento de hacer _hover_.
=> Prevent duplicated CSS & and transition for buttons

src/components/KonamiCode.astro
Por alguna razón, el evento `transitionend` se activa antes de que termine la transición CSS de Konami, como consecuencia, se eliminan los estilos relacionados a la transición antes de que se complete
No encontré algún bug similar en StackOverflow o similares pero está ocurriendo acá como se puede ver en #159
Fixes #159 
1. En lugar de escuchar el evento `transitionend` y allí eliminar los estilos relacionados a la animación Konami, se eliminan si el usuario intenta reproducir dicho efecto, o sea, una vez cumplido el efecto por primera vez, al teclear la primera tecla requerida (Keyup) nuevamente, se eliminan los estilos de la transición anterior para dar pie a la transición nueva al teclear la combinación correcta
https://github.com/midudev/la-velada-web-oficial/assets/70046023/84518b03-3 …
=> fix: konami animation ends early

src/components/ButtonUp.astro, src/components/Date.astro, src/components/HeroLogo.astro, src/components/SmokeBackground.astro, src/components/ThemeToggle.astro, src/sections/Footer.astro, src/sections/Hero.astro, src/sections/Info.astro, src/sections/PrincipalDate.astro
Algunos usuarios suelen tener las animaciones deshabilitadas, por lo que estaría genial respetar eso y evitar las animaciones cuando el usuario ha deshabilitado las animaciones del sistema.
Se han incluido las clases de tailwind `motion-safe:` y `motion-reduce:`, además del CSS media query `@media (prefers-reduced-motion) {}` para incluir animaciones selectivamente.
https://github.com/midudev/la-velada-web-oficial/assets/56328053/94f5e783-ad9b-4d08-ace8-61dfaff38278
https://github.com/midudev/la-velada-web-oficial/assets/56328053/ba37a789-c3e6-49c8-aba6-fc2455766fc3
> Nota: Ambos videos se grabaron con las animaciones desactivadas (Windows 11)
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
https://tailwindcss.com/docs/animation#prefers-reduced-motion
=> Prevent animations when system animations are disabled

src/icons/boxing-gloves.astro, src/icons/instagram.astro, src/icons/la-velada.astro, src/icons/map-marker.astro, src/icons/moon.astro, src/icons/sun.astro, src/icons/weight-boxer.astro, src/icons/x.astro
Changes were made to the implementation of icons to correct the incorrect use of `class` in favor of `class:list`. This improves code consistency and follows best practices.
This change addresses the identified issue in the icon files where `class` was being used incorrectly, generating warnings.
- Fixed the use of `class` to `class:list` in icon files, following Astro's recommendations.
- The following files have been updated: `boxing-gloves.astro`, `instagram.astro`, `la-velada.astro`, `map-marker.astro`, `moon.astro`, `sun.astro`, `weight-boxer.astro`, and `x.astro`.
before
after
These changes are expected to have no significant negative impacts.
These changes are part of a series of improvements to follow best practices and maintain consistency in the codebase.
- [Reference …
=> fix: replace 'class' with 'class:list' in icon files

src/sections/Info.astro
A partir de 1024px de ancho, el link al twitch de Ibai en el `Info.astro` se ve desplazado hacia la derecha porque el ancho del anchor era mayor al del contenedor, el h3.
Fixes #183.
1. Se centra el anchor tag usando flex y justify-center en el contenedor del anchor.
Antes:
Después:
1. A los detallistas compulsivos no les va a titilar el ojo cuando vean que hay algo que no está centrado.
Enlace a la issue que resuelvo: #183
=> Fix issue #183

src/layouts/Layout.astro, src/sections/Hero.astro
Cambié el color azul por defecto al seleccionar el texto de la página para que siga la línea de colores de la web.
- Se agrega en el `Layout.astro` las clases `selection:bg-primary selection:text-secondary` para que herede toda la página
- Se agrega en el `sections/Hero.astro` la clase `select-none` para que no se vea raro al seleccionar el texto que ya tiene un background.
Look original:
Después de los cambios:
El pseudo-elemento `::selection` [no es full compatible con Safari en iOS](https://caniuse.com/?search=%3A%3Aselection)
=> Custom text selection

src/layouts/Layout.astro, src/pages/index.astro
Cuando se ejecutaba la animación del código konami no se limpiaba el estilo transform al terminar, lo que impedía el posicionamiento fijo del componente "ButtonUp" en la página.
- Se movió el componente "ButtonUp" hacia el Layout para quedar fuera del contenedor que gira al ejecutarse la animación del código konami
En ambos casos las capturas se tomaron al terminar la animación
Antes (aunque se hiciera scroll hacia arriba, el componente se quedaba dentro del footer)
Después
=> Fix ButtonUp position while executing konami code

src/components/Date.astro, src/sections/Countdown.astro
Esta pull request se centra en arreglar el problema de las transiciones del contador. Este se movía hacia arriba demasiado rápido y había números no utilizados por el sistema sexagesimal que usa el tiempo y las 24 horas que tiene un día.
Se ha solucionado el problema de las transiciones del contador que se hacían en velocidades distintas y a veces podría llevar al mareo. Esto sucedía cuando una cifra pasaba del 0 al 9 (o del 0 al 5, dependiendo de si eran segundos, minutos...). Más adelante están las capturas con la comparación de los cambios.
1. Añadir un 0 al final del todo que se  cambia por el 0 de arriba del todo sin transiciones cambiando las clases de tailwind. 
2. Añadir una propiedad max para no repetir números y que las transiciones sigan funcionando sin ir rápido.
**ANTES:** …
=> Improved countdown for more natural transitions

src/consts/event-date.ts
Se cambian las abreviaciones de los paises de LATAM con solo una timezone por el country code. Con esto de mejora la identificacion.
Fuente: [Sanidad Española](https://www.sanidad.gob.es/ciudadanos/saludAmbLaboral/docs/codigoIsoPai.pdf)
Estos cambios no implican un impacto potencial en le rendimiento de la web. Estos cambios solo aplican sobre la usabilidad de la misma.
=> Cambio a country codes en paises de LATAM

src/components/TwitchLogo.astro
Se evita que el scroll animation ocurra cuando las animaciones del sistema están explícitamente deshabilitadas.
La animación en cuestión, es el cambio del color de relleno del SVG del logo de Twitch al hacer scroll.
Antigua PR relacionada: https://github.com/midudev/la-velada-web-oficial/pull/173
=> Prevent scroll animation if system animations are disabled

src/sections/Countdown.astro
Alinea el texto que anuncia que la presentación ha empezado para mejor visualización en movil
En movil el texto "¡EL EVENTO DE PRESENTACIÓN HA EMPEZADO! 🎉" aparecía posicionado hacia la izquierda en
lugar de aparecer centrado
se añade la clase "text-center" de Tailwind en la creacion del elemento
Antes:
Ahora:
Nada mas alla de la apariencia
=> add text-center for phone view

src/sections/Hero.astro
Fix #211 
Se redujo el tamaño máximo del logo (y el _X Drawn_) en pantallas pqeueñas
=> Fix mobile layout

src/sections/Sponsors.astro
Modifique algunos nombres de clases para evitar el AD blocker
Se resuelve el problema mencionado en la issue [El AD blocker remueve los logos de los sponsors #237
](https://github.com/midudev/la-velada-web-oficial/issues/237)
- Se renombro las clases que contenian la palabra sponsor por company para evitar el AD blocker.
Antes:
[screen-capture.webm](https://github.com/midudev/la-velada-web-oficial/assets/35277540/9164e84b-5d40-4e75-83ae-cb0494068d9d)
Despues:
[ad-blocker-solve.webm](https://github.com/midudev/la-velada-web-oficial/assets/35277540/1a8e0500-462a-4a78-a065-6552b4caaa58)
=> fix: Update sponsors class names to avoid the ad blocker

src/sections/PrincipalDate.astro
Agregue algunas clases de tailwind en la etiqueta time del component `<PrincipalDate />`
Un pequeño salto en el texto de 13 de Julio
Agregue la class inline-block en la etiqueta time:
```html
<header class="text-3xl font-semibold uppercase md:text-5xl">
<time class="date inline-block"></time>
</header>
```
Y también agregue un `classList.remove` en el JavaScript:
```js
if ($timeSpan != null && showTime) {
$dateSeparator?.classList.remove("hidden")
}
```
=> Add styles to fix a text time break 

src/sections/Sponsors.astro
Añadir padding a los logos de los esponsors para que se vea bien en pantallas más pequeñas
Antes:
Despues:
=> responsive: add padding on sponsors logos

.github/issue_template.md
Template para crear issues
- Agregué un template para poder crear issues y que esten más detallados para poder reproducirlos
- [Issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
=> Add `ISSUE_TEMPLATE`

src/layouts/Layout.astro
Realize solo un cambio en el overflow del body (overflow-x-hidden), haciendo que este no pueda scrollear horizontalmente en ningun tamaño de pantalla
Soluciona #277
Mas detalle:
El problema se origina en celulares y tablets.
Iphone 14 Pro Max:
Ipad mini:
Como se puede notar el contenido no esta centrado.
- En el body (Layout.astro) poner la clase overflow-x-hidden
Las siguientes imagenes son del despues:
Iphone 14 Pro Max:
Ipad mini:
- [ x] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ x] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [x ] He actualizado la documentación, si corresponde.
Arreglar la visualización en pantallas móviles y prevenir que en …
=> fix(responsive): make content be always centered #277

src/components/Typography.astro
The component now need less code to do the same and props are typed.
variant and color overwrite types is needed because a bug of Astro that type Astro.props as any instead as T [Issue 10347](https://github.com/withastro/astro/issues/10347)
Props no tienen tipos
Se han corregido los tipos y eliminado codigo innecesario
```astro
---
import type { HTMLTag, Polymorphic } from "astro/types"
type Props<Tag extends HTMLTag> = Polymorphic<{
as: Tag
variant: keyof typeof variantClasses
color: keyof typeof colorClasses
}>
const { as: Tag, class: className, variant, color, ...props } = Astro.props
const variantClasses = {
h2: "text-lg font-medium uppercase lg:text-2xl",
h3: "text-2xl font-semibold uppercase",
body: "text-xl",
medium: "text-md",
}
const colorClasses = {
white: "text-white",
black: …
```
=> refactor(Typography): add types and removed unnecessary code

src/components/ButtonUp.astro, src/components/NoiseBackground.astro, src/components/SmokeBackground.astro
Traduje las etiquetas aria-label a español, ya que estaban en inglés.
Ahora las etiquetas de accesibilidad están en español como corresponde, ya que es una página orientada a un público español.
Cambiar las aria-label en inglés a español.
Mejorar accesibilidad
- Documentación del proyecto:
=> Traducir etiquetas a11y a español

src/sections/Hero.astro
Modifiqué el tamaño del texto del link al canal de Ibai encima del logo para que siga el diseño original.
Antes:
Después:
=> fixing twitch/ibai text mobile responsive

src/components/CalendarButton.astro, src/sections/PrincipalDate.astro, tailwind.config.mjs
Tailwind media query *xs* for screen width size <= 360px. 
fix: action buttons now do not overflow the screen (font size fixed at 16px when width screen is < 360px)
screen size of tested  device: 320x568
before: 
after:
=> Responsive for width < 360px

src/layouts/Layout.astro
Agregue el tag link preload para la fuente atomic.woff2
Ayudar un poco con la carga de la fuente atomic.woff2
=> Fix tag link preload font atomic

src/sections/Footer.astro
Arreglo de color de los iconos del footer
He eliminado el estilo de reducción de opacidad de los iconos al hacer hover ya que esto hacía que el color de los iconos no coincidiera con el color resaltado
**Antes:**
**Después:**
=> Fix footer icons color on hover

src/components/LiteYouTube.astro
Se agregó el atributo role al elemento <lite-youtube> con el propósito de mejorar la accesibilidad para usuarios que utilizan tecnologías de asistencia, como lectores de pantalla. Esto ayuda a clarificar la función y el propósito del elemento, lo que contribuye a una mejor experiencia de usuario en general.
Al agregar los atributos role y tabindex al elemento <lite-youtube>, se resuelve un problema de accesibilidad al hacer que el reproductor de video de YouTube integrado sea más usable para personas con discapacidades visuales o que dependen de la navegación por teclado.
https://developer.mozilla.org/es/docs/Web/Accessibility/Understanding_WCAG/Keyboard?utm_source=devtools&utm_medium=a11y-panel-checks-keyboard#Clickable_elements_must_be_focusable_and_should_have_interactive_semantics
=> feat(LiteYouTube): :wheelchair: add role and tabindex attributes to lite-youtube for improved accessibility

src/sections/Sponsors.astro
Siguiendo el estilo de la PR https://github.com/midudev/la-velada-web-oficial/pull/326, añadí select-none a los sponsors y al logo de InfoJobs, ya que son imágenes.
Antes
Después
PR https://github.com/midudev/la-velada-web-oficial/pull/326
=> fix: add select-none to sponsors and infojobs logo

src/components/LiteYouTube.astro
He agregado un event listener para poder reproducir el vídeo utilizando la tecla enter tras seleccionarlo en caso de no poder usar el mouse, ya que no se podía realizar anteriormente.
Además traducí un par de labels a11y a español.
- Agregar event listener a vídeo para reproducir el vídeo en caso de seleccionarlo y presionar enter (se pueden agregar más teclas a la función en caso de desearlo)
- Traducir labels a11y a español
Mejorar la accesibilidad para todos los usuarios.
=> (a11y) Arreglar vídeo para que se pueda reproducir presionando enter

src/sections/Info.astro
hay que revisar las tipos ya que no se pueden poner mayus (supongo que algo de la optimización
Básicamente cambiar la letra E a e ya que con Atomic queda rara (supongo que se ha optimizado la fuente para quitar mayus)
Básicamente cambiar la letra E a e ya que con Atomic queda rara (supongo que se ha optimizado la fuente para quitar mayus)
Básicamente cambiar la letra E a e ya que con Atomic queda rara (supongo que se ha optimizado la fuente para quitar mayus)
Antes:
Después:
- [x ] He actualizado la documentación, si corresponde.
No hay
No necesario
No …
=> [FIX] letter e info section

src/pages/404.astro, src/sections/Error.astro
Mejoras en la UI de la página NotFound para que se vea más llamativo y sea mas entendible por el usuario agregando una breve descripción del error
El mensaje de notfound se mostraba abajo y sin mucho contexto. En la nueva versión se le muestra un mensaje al usuario en el top de la página junto al botón de volver
**Uso del Typography en lugar de los h1 que habían anteriormente
Creación de un nuevo parámetro llamado contextMessage, donde le damos información al usuario del error
Flex horizontal para vistas en PC, y con wrap para vistas móviles**
**Interfaz original:**
**Interfaz con mejoras:**
- [Sí ] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [Sí ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la …
=> Mejoras de UI al error 404 Not Found

src/components/LiteYouTube.astro
El elemento lite-youtube en el componente LiteYoutube no tiene un nombre accesible debido a que no tiene un aria-label y el span que se encuentra dentro tiene un texto vacio. 
Como el componente recibe un `title` en sus props que no se está usando, ajusté el código para que este texto sea el que usa el elemento anchor dentro de lite-youtube, y para no modificar el archivo donde se utiliza ese componente, indiqué que el valor por defecto de título sea "Reproducir presentación de La Velada del Año", texto que estaba escrito en duro en el código, de esta manera el componente se hace reutilizable y el elemento lite-youtube reconoce el contenido del span como texto descriptivo accesible
El elemento lite-youtube en el componente LiteYoutube no tiene un nombre accesible
- Usar el `title`, que …
=> update LiteYouTube component for accessibility

src/sections/Error.astro
He añadido `overflow-visible` para solucionar un corte del blur en el HeroLogo de la pagina de Error404
Corte del blur en el componente `HeroLogo` de la pagina de Error404
Se añade `overflow-visible` en el componente `<HeroLogo>` del archivo `Error.astro` porque si no se corta el blur del logo principal en la pagina del error404
No debería tener ningún impacto potencial
- Documentación del proyecto:
=> Fix: Blur of the logo cut on error404 page

src/components/Action.astro, src/components/CalendarButton.astro, src/sections/Error.astro, src/sections/PrincipalDate.astro
Ajuste en la implementación del componente Action.astro.
Existe css que no está siendo utilizado y css que no es necesario utilizar.
Se mueven etiquetas `<span>` dentro del componente para que carguen correctamente los estilos (Deja recto el texto).
- Antes
- Después
- Antes
- Después
Al hacer `:hover` causaba ciertos saltos en el texto mientras se reproducía la animación, esto lo corrige. 👍
=> Se ajusta componente Action

src/sections/Hero.astro
Se agrego una mejora en los estilos del link que lleva al canal de ibai
Se agrego una mejora en los estilos del link que lleva al canal de ibai en la sección Hero.
Mejora visual del hover. 
1.  Se agregaron estilos para que el subrayado del link aparezca de izquierda a derecha y parezca un poco más fluido.
Antes
https://github.com/midudev/la-velada-web-oficial/assets/65756460/95c0310b-a349-4269-b9aa-6f55f46370a1
Despues
https://github.com/midudev/la-velada-web-oficial/assets/65756460/18f12d85-7b29-4647-a737-7624f0daa133
Es solo una mejora visual en cuanto a la experiencia de usuario.
-
-
=> Update Link Hero.astro

src/components/ButtonUp.astro
Para seguir la convección del color "accent" en los iconos y algunos botones, agregué el color en el hover del ButtonUp
El ButtonUp no llevaba el color "accent"en el hover.
1. Agregar color "accent" en el hover del ButtonUp
Antes:
Despues:
Es mi primera PR en la vida siguiendo el Curso de GIT desde cero en tu canal <3
=> Agrego color al hover del ButtonUp

src/sections/Info.astro
Eliminé un anchor redundante (Logo de Twitch) en la sección "En Directo" del tabindex y accessibility tree para mejorar la experiencia de usuario. Ya hay otro anchor abajo que cumple la misma función.
Antes
[antes.webm](https://github.com/midudev/la-velada-web-oficial/assets/133175356/1e0fa2d2-abd3-45af-bf68-65c862313bcc)
Después
[despues.webm](https://github.com/midudev/la-velada-web-oficial/assets/133175356/81518583-9307-49e1-8646-7ea46c507f4c)
=> fix: remove redundant anchor from tabindex and accessibility tree

src/layouts/Layout.astro
Un pequeño detalle, pero que aporta. Cambio de color al hacer clic en la barra de desplazamiento.
- Cambio de color en la barra de desplazamiento.
- Antes
- Después
=> styles: Change color of scrollbar when clicked

src/sections/PrincipalDate.astro
He actualizado el efecto de subrayado en la sección 'ESTADIO SANTIAGO BERNABÉU' para que ahora presente una animación que se integre armónicamente con las demás animaciones presentes en la página web.
He realizado dos commits para esta actualización. En el primero, implementé un efecto de subrayado con gradiente, y en el segundo, eliminé el gradiente para crear un subrayado más sencillo.
El problema que se ha solucionado es que el efecto de subrayado anterior no estaba en armonía con el diseño general de la página web, por que no se ajustaban al estilo visual del resto de animaciones. Al actualizar el subrayado, se ha logrado una cohesión visual más consistente con el diseño general del sitio web.
Los cambios propuestos implican actualizar el efecto de subrayado en la sección "ESTADIO …
=> Update link animation

src/sections/Info.astro
Homogenizar ambas url con el subdirectorio www. 
Actualmente una lo tiene y otra no, y www.twitch.tv/ibai es realmente la pagina final a la que el usuario acaba siendo redirigido de todos modos.
=> Ambas url con www.

src/consts/sponsors.ts, src/sections/Sponsors.astro
Añadidos alto y ancho de las imágenes en `src/consts/sponsors.ts` y una interface para el tipado con TypeScript.
> El alto dado es el máximo de uno de los sponsors, no cambia el alto de la imagen perse
interface Sponsors:
```typescript
interface Sponsors {
id: string
name: string
url: string
image: {
width: number | string
height: number | string
}
}
```
> width y height tienen como opción string por si se decidiese poner por ejemplo: 128 o "128" o "auto"
Problema con LightHouse First Contentful Paint detallado en #366 por @midudev
1. Añadir `interface Sponsors` en `src/consts/sponsors.ts"
2. Añadir entrada de `image: { width, height } en cada sponsor
3. Aplicar los cambios en `src/sections/Sponsors.astro` 
Mejorar a la performance de la página
=> fix(#366): Added implicit sponsors images' width and height

src/sections/Sponsors.astro
Arreglado powered by infojobs xs media query
Arreglado powered by infojobs xs media queryenlace al problema si existe. -->
Pasar de flex row a col cuando es menor de xs
Antes:
Despues:
No debería
=> [FIX] powered by infojobs

src/components/LiteYouTube.astro
Agregué la tecla espacio a las teclas que activan el vídeo al enfocarlo, ya que igual se usa para este propósito.
=> fix: handleKeyPress now handles space

src/sections/Info.astro
Cambié los dos anchors a solo uno en `Info.astro` para eliminar una zona muerta que había donde el anchor no funcionaba, a pesar de tener el efecto de hover como que sí funcionara. El estilo quedó idéntico.
Antes:
Después:
=> fix: Eliminar zona muerta en anchor

src/sections/Info.astro
Se corrige al centrar verticalmente el logo de Twitch en diferentes dispositivos. Sin la necesidad de hacer cambios sustanciales al código. Además el efecto hover es visualmente atractivo al usuario.
https://github.com/midudev/la-velada-web-oficial/assets/57963142/2996dfe7-a595-49e1-ba56-ae3a92efe41c
Mejora UX.
=> Fix: Center TwitchLogo

src/components/LiteYouTube.astro, src/sections/Footer.astro
Algunos elementos tenían una variante del color definido como `--color-accent`. Para mantener la uniformidad de colores en la página, se ajustaron algunos elementos que no coincidían con el original.
El color del botón _play_ del reproductor del video de la Presentación de La Velada IV así como los iconos de enlace a Instagram, X y Github no utilizan el color `--color-accent`.
1. Se ajustó el atributo `fill` del SVG del componente LiteYouTube al estar en _hover_.
Dado que no es posible utilizar variables de CSS en los atributos de un SVG insertado como `background-image`, y que es muy poco probable que la definición de `--color-accent` cambie pues es uno de los colores principales de la paleta de La Velada IV se escribió directamente el código hexadecimal de este.
2. Se eliminaron los …
=> Ajusta color `hover` de algunos elementos

src/components/LiteYouTube.astro
Se agrega un borde redondeado al componente `lite-youtube`, junto con una mejora en el color del borde (`border`), sombreado (`shadow`) y del icono de reproducción (`play`).
1. Se incorpora un borde redondeado para mejorar la estética (`class: rounded-lg`).
2. Mejora en el color de los siguientes elementos:
1. `border`: Se utiliza el color específico de la aplicación.
2. `shadow`: Se aplica el mismo color de la aplicación para el sombreado.
3. `play`: Se añade el color correspondiente de la aplicación al ícono de reproducción al pasar el cursor sobre el componente.
***Antes***
***Ahora: No `hover`***:
***Ahora:  `Hover`***:
=> `lite-youtube`: Add rounded border and improved color border, shadow, play

.github/pull_request_template.md, CONTRIBUTING.md
Mantener a la comunidad unida a la hora de crear PRs
Hay muchas PRs que se abren habiendo otras ya abiertas, en vez de aportar a las que están abiertas con comentarios, sugerencias, revisiones ...
1. Reducir número de PRs a revisar.
2. Fomentar colaborar entre personas en una misma PR si han tenido una idea similar.
3. Mejorar la experiencia de desarrollo, algunos comandos útiles.
Estas 3 PRs tienen el mismo fin, cada una con su variante "artística" pero con el fin de crear cohesión con el diseño global de los links que se encuentran en la sección `Hero.astro`.
Estaría bien, ver que hay una primera abierta y trabajar las 3 personas en conjunto, en vez de crear PRs adicionales que hacen que haya más PRs a revisar.
Reducir el número de PRs abiertas y que tienen que ser revisadas, fomentando …
=> doc: Ensure good practices and improve DX

src/components/LiteYouTube.astro
He cambiado el color de la barra del reproductor del video.
La barra del reproductor del video en color blanco encaja mejor con el diseño de la web.
Antes
Ahora
- [Youtube API de IFrame](https://developers.google.com/youtube/player_parameters#Parameters)
- [Lite youtube embed](https://github.com/paulirish/lite-youtube-embed/tree/master)
=> change player bar

src/components/LiteYouTube.astro
Al hacer click se oculta la imagen de previsualización de `src/components/LiteYouTube.astro`
Al redimensionar el vídeo se quedaba la imagen por detrás y no se redimensionaba a la vez.
1. `background-image: unset !important`
Antes:
Ver el Issue #401
Después:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/eda8074e-38ee-4b4e-b8a2-8d43da6a67fc
Mejora del rendimiento y la experiencia de usuario
=> fix(#401): resizing bug on resize

src/components/AnimatedX.astro
Añadir tipos más explícitos que `any`
Aprovechar el tipado de TypeScript y comprobar si el elemento seleccionado es o no es nulo.
1. Añadidos tipos para no tener que usar `any`
Si se decide modificar el componente, el desarrollador tendrá mejor autocompletado y se podrá detectar si hay algún problema al seleccionar un elemento que no exista.
=> feat: Improved `src/components/AnimatedX.astro` typing

src/sections/Hero.astro
Mejorado la transición del subrayado en el hover, manteniendo la consistencia con la transición de subrayado del enlace del Santiago Bernabéu de la PR #375.
Cambio para que la transición del subrayado comience y termine de izquierda a derecha cambiando la propiedad por defecto a ```transform-origin: right;``` y al hacer hover cambie a ```transform-origin: left;```.
https://github.com/midudev/la-velada-web-oficial/assets/151189780/ae5ae639-4d35-4b48-868f-f8b184486655
https://github.com/midudev/la-velada-web-oficial/assets/151189780/f7fe2ce8-a045-4877-9218-84d9b9aceca2
=> Enhanced: Improved underline transition twitch link

src/sections/Boxing.astro, src/sections/Countdown.astro, src/sections/PresentationVideo.astro, src/sections/PrincipalDate.astro, src/sections/Sponsors.astro
Se ha arreglado el espacio entre secciones, ya que la diferencia era muy bestia.
Se ha arreglado el espacio entre secciones, ya que la diferencia era muy bestia.
Arreglar el espacio entre secciones
Antes:
Después:
=> [FIX] matching gap sections

CONTRIBUTING.md, README.md
Actualicé la documentación del proyecto cambiando `git checkout` por `git switch` tanto en el README como en el CONTRIBUTING
Actualización de la documentación
Git recomienda usar `switch` en vez de `checkout`
=> Fix README and CONTRIBUTING - Replace git checkout with git switch

src/components/Date.astro, src/components/LiteYouTube.astro, src/sections/Countdown.astro, src/sections/PrincipalDate.astro
Arreglar el tamaño del nuevo boton para que sean los dos iguales.
Arreglar el tamaño del nuevo boton para que sean los dos iguales.
- Usar el mismo Action component pero arreglar el size para que sean los mismos.
BEFORE: 
AFTER:
- [✅] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [✅] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [✅] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- none.
=> fix: different size of "ir a la tienda oficial" button

src/components/Date.astro, src/components/LiteYouTube.astro, src/sections/Countdown.astro, src/sections/Hero.astro, src/sections/PrincipalDate.astro
Añadido soporte para reducción de animaciones.
Con los cambios introducidos para la consistencia de links, no se añadió soporte a las personas que tenga activada la reducción de animaciones.
1. Añadir `@media (prefers-reduced-motion)`
2. Como en la PR #422, se podría crear un estilo global con ello. (A la espera de comentarios para implementarlo o ayudar en esa PR)
Sin reduced motion:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/1ecab578-b8c3-4421-a313-d94ebab1c167
Con reduced motion:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/37892a9f-815a-4e57-89b3-587d697ea594
Mejorar la accesibilidad de las personas que tengan reducción de animaciones.
=> feat: add reduced motion support

src/components/Date.astro, src/components/LiteYouTube.astro, src/sections/Error.astro
Añadir el `--color-accent` al tipo de error y hacer logo clicable.
Hasta ahora, quedaba muy plano. Con este cambio se asegura mejor reconocimiento del error y mejorar la experiencia de usuario, habilitando el uso del logo como volver a la landing.
Antes:
Después:
Mejorar el reconocimiento de errores y la experiencia del usuario. Al ser una práctica extendida el uso del logo como vuelta a la landing.
=> feat: 404 modified design

src/components/ImageOverlay.astro
Añadido select-none a ImageOverlay para seguir la línea de diseño de no poder seleccionar imágenes.
Antes
Después
=> fix: add select-none to ImageOverlay img

src/components/ImageOverlay.astro, src/sections/Boxing.astro, src/sections/PresentationVideo.astro
Hacer que la sección de links se asemeje un poquito más al resto de secciones y al diseño del figma.
El diseño de la sección de links no acababa de encajar con las medidas y diseño del resto de la web y figma.
Modificar estilos para hacer que cuadre
Antes:
Después:
No debería.
=> Section links - Hacer que se asemeje un poco más al figma y al resto de seccions

.husky/pre-commit, .lintstagedrc, package.json
Como me dijo @joelmh-112 en 2 PRs, tenía que añadir cambios porque prettier se quejaba de fallos de formato en archivos en los que no estaba trabajando.
Con [lint-staged](https://github.com/lint-staged/lint-staged), este problema se solucionaría.
Además de mejorar la experiencia de desarrollo.
1. Solo lintear y comprobar en archivos que se van a añadir al commit.
2. Reducción de tiempos de espera a la hora de de hacer un commit, ya que no mirará en todos los archivos, solo los que estén `staged` o añadidos al commit.
Vídeo sobre esta dependecia:
<a href="https://www.youtube.com/watch?v=YWBrzwSDp" target="_blank" rel="noopener noreferrer">
</a>
Reducir tiempo en el desarrollo y asegurar que no se producen commits innecesarios.
Mejorar la adición de features como por ejemplo: si añadimos …
=> feat: add lint staged pre commit

src/components/Glow.astro
Componente para crear un efecto Glow parecido al que se usa en el logo, cartelería etc para usar en cajas. COmo por ejemplo en el video
Creación de un componente llamado Glow
https://github.com/midudev/la-velada-web-oficial/assets/13372238/10d0bd05-225a-4b04-b25e-d5b1a7f345a3
Ejemplo de uso en el vídeo de youtube
=> Add Glow component for creating glowing effects

src/components/LiteYouTube.astro
Anteriormente al hacer `hover` sobre el botón de _play_ del video de la Presentación de La Velada, se mostraba en Safari un parpadeo.
En Safari, el botón de _play_ del reproductor del video de La Velada parpadea al hacerle `hover`.
1. Se eliminó una propiedad de transición declarada para las clases `lite-youtube:hover > .lty-playbtn, ite-youtube .lty-playbtn:focus`. Esta propiedad queda implícitamente definida en `lite-youtube > .lty-playbtn`, provocando que Safari malinterprete el efecto.
(Se cambió el color del icono en el video para hacer más evidente el parpadeo).
- Antes:
https://github.com/midudev/la-velada-web-oficial/assets/12474344/69e60bf2-7ca4-4be7-b533-6be48d6e1a2f
_El parpadeo se da en este punto_:
- Ahora:
https://github.com/midudev/la-velada-web-oficial/assets/12474344/12cc8 …
=> Corrige parpadeo del botón 'play' en Safari

src/layouts/Layout.astro
Se eliminaron las propiedades que deshabilitaban el pull to refresh en navegadores móviles.
Pull to refresh deshabilitado en navegadores móviles. #415 
Se eliminó la propiedad overflow-x del elemento body y las propiedades overflow-x y overscroll-behavior del elemento html.
https://github.com/midudev/la-velada-web-oficial/assets/79766563/efc7c47a-09a2-4088-8d2f-f92e17fcd34b
Mejora experiencia de usuario.
=> fix: mobile pull-to-refresh

src/components/RichResults.astro, src/components/SEO.astro
Se corrigio la dirección de la imagen en las etiquetas meta og
La url apuntaba a https://lavelada.es/og.jpg lo cual daba un 404. Se cambio a "/og.jpg"
<meta name="twitter:image" content="/og.jpg" />
- [ x] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
=> Fix images path to relative URL in head

src/sections/PresentationVideo.astro
Se había quitado el overflow hidden de la seccion presentation video en una pr que tocaba un montón de cosas. Hay que ponerlo para que no se rompa el responsive de dicha sección, ya que hace que toda la web se vea mal.
=> [FIX] overflow hidden reverted error

src/components/Date.astro
Arreglado error, los números superiores e inferiores de la cuenta atrás podían seleccionarse con el ratón
los números superiores e inferiores de la cuenta atrás podían seleccionarse con el ratón
corregir la altura de su span y añadir display: hidden
=> fix: los números superiores e inferiores de la cuenta atrás podían seleccionarse con el ratón

src/layouts/Layout.astro
Añadido estilos al scrollbar cuando el selector `::webkit-scrollbar` no está soportado, como por ejemplo en Firefox. Priorizando los estilos del **webkit-scrollbar** cuando esté soportado.
Utilizar el `@supports selector(::-webkit-scrollbar)` y el `@supports not selector(::-webkit-scrollbar)` para aplicar los estilos al scrollbar.
- Antes
- Después
=> feat: add scrollbar style when webkit-scrollbar is not supported

src/sections/SelectYourBoxer.astro
Linear gradient toma más espacio del que debería 
Cambio el linear-gradient del fondo de los boxeadores por el radial
- [ ✅] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [✅ ] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ ✅] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
=> style: add radial-gradient to the boxer background image

src/sections/SelectYourBoxer.astro
Agregar efecto de blanco y negro a color cuando el boxeador esta activo
Agregado la class active al box-link cuando hace mouseenter y un mouseleave para quitar la class de esta forma tendremos a todos los boxeadores desactivados y el cuando hagamos hover se vera como seleccionado
=> Add active class to boxer links and update image filter

src/pages/boxers/[id].astro
Se cambia la info hardcoded por la info dinamica
Se mostraba la misma información para todos los boxeadores y se sustituye por la info real
- Leer id del boxeador
- Cambiar información hardcodeada por la del boxeador según el id
NA
NA
NA
=> Usar la información del boxeador en la pagina boxer

src/sections/SelectYourBoxer.astro
He cambiado el fallback de .avif a .webp ya que tanto la etiqueta source como la etiqueta img apuntaban al mismo recurso.
En principio ponemos los dos por si el navegador no puede cargar uno de ellos
=> Arreglando la imagen fallback de SelectYourBoxer

src/components/ImageOverlay.astro
He cambiado el Height del componente ImageOverlay
Al estar el Height en auto, los textos no cuadraban entre si. He puesto que este sea de 40 y asi estas se ven en linea (tambien cambie el w-full a w-auto por que sino la imagen se corta)
Antes:
Después:
=> Update ImageOverlay Height

src/components/SEO.astro
Se implementa la solución sugerida por @Cristian021195 en el issue #462 en donde se precarga la fuente Atomic para evitar el salto de fuente, especialmente en el texto "twitch.tv/ibai"
https://github.com/midudev/la-velada-web-oficial/assets/30879476/f83b7b70-e422-4489-af4b-ff12c2d8b9c0
https://github.com/midudev/la-velada-web-oficial/assets/30879476/4fdf7d09-899a-42ae-af22-d16eaba63de3
=> Fix: Precarga de la fuente Atomic para evitar salto de fuente

src/components/Date.astro
Desactivada la opción del usuario de seleccionar los números del countdown mediante el uso de la clase select-none de tailwindcss
=> Desactivada la opción del usuario de seleccionar los números del countdown

src/sections/Footer.astro
Use the same resource of the horizontal rule in the page footer.
- Add hr
- Add more spacing
=> Add horizontal rule

src/pages/boxers/[id].astro, src/sections/SelectYourBoxer.astro
He añadido las descripciones de los boxeadores.
No estaban implementadas toda la descripción de cada boxeador.
Añadí el nombre real, el peso la altura y el país del boxeador.
Ordenador:
Móvil:
- [*] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [*] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
=> Id boxer description

src/sections/Countdown.astro
Se ha agregado la clase "select-none" para asi evitar que el usuario seleccione el countdown.
ANTES:
AHORA:
- [x ] He actualizado la documentación, si corresponde.
=> Add: User Selected None to CountDown.

src/sections/SelectYourBoxer.astro
Se resolvió un memory leak causado al hacer hover en cada card de los luchadores.
El problema abordado en esta solicitud de extracción es un memory leak que ocurría cuando se pasaba el cursor sobre las tarjetas de los luchadores. Este problema podría provocar un consumo excesivo de memoria y un rendimiento degradado en la aplicación.
Se modificó el código que maneja el evento `mouseenter` y `mouseleave` en los enlaces de los luchadores. Se introdujo una variable `timeout` que almacena el ID del temporizador (`setTimeout`) utilizado para retrasar la actualización de la información del luchador. Al salir del enlace (`mouseleave`), se limpia el temporizador utilizando `clearTimeout(timeout)`. Esto garantiza que no haya temporizadores pendientes que puedan causar fugas de memoria.
No se prevé …
=> Fix de memory leak al hacer hover en cada card de los luchadores

src/sections/SelectYourBoxer.astro
Se ha añadido el peso y el país para que salga al posicionar el ratón encima de la imagen de un boxeador (salen sus datos específicos). Esta es una nueva implementación de la Pull Request [#454](https://github.com/midudev/la-velada-web-oficial/pull/454) que hice.
Se ha añadido el peso y el país para que salga al posicionar el ratón encima de la imagen de un boxeador (salen sus datos específicos).
=> Peso y País del boxeador (mejora del PR #454)

src/consts/boxers.ts
Se ha cambiado el orden de los boxeadores para que la vista quede simétrica.
Al salir los boxeadores de perfil queda raro que miren indistintamente a un lado o a otro.
Se ha reordenado el array de los boxeadores sobre el que se itera para pintar el componente de Selector de Boxeador.
ANTES:
DESPUÉS:
ALTERNATIVA (todas hacia el mismo lado haciéndole mirror horizontal a algunas imágenes)
Ningún impacto.
=> Cambiar orden boxeadores para que quede simétrica la vista

src/components/SmokeBackground.astro, src/layouts/Layout.astro, src/sections/Footer.astro
Esta pull request elimina el código muerto de la pre-landing para cambiar entre el tema claro y oscuro.
Uso del tema claro/oscuro que había en la pre-landing.
Eliminación de las clases 'dark' de tailwind y modificación de un aria-label en el footer.
No se modifica nada visualmente.
=> Eliminación de Código Muerto de la Pre-Landing

package.json
Se actualizó la versión de Astro a la última versión donde la transición de los boxeadores funciona perfecto. Me refiero a la versión `4.3.7`
Es decir, las transiciones dejan de funcionar a partir de la versión[ `4.4.0`](https://github.com/withastro/astro/releases/tag/astro%404.4.0) (Útil saberlo si se quiere abrir una issue)
=> Upgrade astro to latest safe version

src/sections/Countdown.astro
FIX - se arregla que el countdown se pone a cero debido a las view transitions
FIX - se arregla que el countdown se pone a cero debido a las view transitions
Poner el listener de astro:page-load para recargar script
No debería
Como ha explicado midu en el directo de hoy cuando se cambia de pagina utilizando las view transitions hay que recargar el javascript con el listener de page-load, sino se queda corrupto.
=> [FIX] countdown setting to 000 when view transitions used

src/sections/Countdown.astro
El componente Countdown en môvil no era como el Figma, estaba dividido en una grid 2x2.
La grid ahora es siempre de 3 columnas y en móvil no hay gap entre estas como en el Figma.
Antes:
Ahora:
=> Fix Countdown component for responsive like Figma

src/sections/SelectYourBoxer.astro
Agregar Link del perfil de cada Boxeador al apartado ver perfil
No se puso el link en ese apartado
=> minifix: Actualizar link de ver perfil en el <a> de ver perfil del article

src/sections/SelectYourBoxer.astro
Con la idea de usar mas extensivamente Tailwind dado que es el framework CSS con el que cuenta el proyecto, cambie algunas declaraciones de estilo de CSS por su respectiva clase de Tailwind en el archivo `SelectYourBoxer.astro `
=> Cambio de propiedades de CSS por clases de Tailwind en SelectYourBoxer

src/consts/sponsors.ts
Cambio extremadamente pequeño, pero el nombre del patrocionador es ElPozo, sin espacio.
Como aparece en el sitio web:
En LinkedIn:
PDF oficial (aparece mencionada como ElPozo): https://www.elpozo.com/wp-content/uploads/2020/11/dossier-sostenibilidad-es.pdf
=> fix: ElPozo grammar

src/sections/Sponsors.astro
Añadí los efectos (transforms) que se producían en `:hover` al `:focus` también en los Sponsors.
Antes:
Después:
=> feat: add hover transforms to focus

src/components/Action.astro
Se elimina CSS para usar Tailwind CSS en su lugar, en el componente ```Action.astro```.
Vídeo para demostrar que no se cambia el diseño del componente, a excepción de la duración de las transiciones, ya que tenía distintos tiempos de duración en CSS y en las clases de Tailwind. Por lo tanto, se optó por la duración de los estilos en CSS, que a mi parecer se ve mejor.
https://github.com/midudev/la-velada-web-oficial/assets/79766563/a2faf2b8-2122-4eec-acab-4ec7776f88a5
=> refactor: remove CSS to use tailwindcss

src/sections/Sponsors.astro
Toc visual del logo de Maxibon que se quedaba solo + reducción de scroll en mobile como consecuencia
El logo de Maxibon se quedaba descolgado provocando que el diseño pesase mas en el lado izquierdo
Se propone aumentar a 3 las columnas en mobile y reducir el gap
Antes:
Ahora:
=> minifix: Reducir scroll y peso visual en la versión mobile de los Sponsors

src/components/Header.astro
Cambiar el menú de flex a grid para poder solucionar layout shifting #513 
layout shifting #513
Cambiar parte del menú de flex a grid
=> [FIX] layout-shifting-header grid instead flex

src/components/Header.astro
En algunas resoluciones mas bajas, cuando el texto del menu de navegación pasa a ser de mas de una línea, no se veia centrado.
Se ha centrado el texto para que almenos en esas resoluciones se vea un poquito mejor.
=> Fix: Center Navigation text when it's wrapped

src/components/KonamiCode.astro
El audio de ibai es demasiado fuerte al iniciar el código "midu", se puede bajar el audio a 0.5 por el motivo de que sea molesto para el usuario
Agregamos en el componente el volumen = 0.5
=> fix the ibai audio volume very loud when starting

src/components/Comments.astro, src/sections/Comment.astro
Agregue la sección de comentarios para la pagina de los boxeadores 
Nueva seccion de comentarios para la pagina de los boxeadores 
- [ x] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ x] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [ x] He actualizado la documentación, si corresponde.
Para habilitar la sección hay que agregar el componente no lo agregue para que no tuviera conflictos con los cambios que están haciendo …
=> Add new  comments section of page boxer

src/components/Header.astro, src/layouts/Layout.astro
He añadido la propiedad scrollbar-gutter tanto en el elemento HTML principal como en el contenedor del menú de navegación para dispositivos móviles.
Efecto de Layout Shift que se producía al abrir el menú de navegación en modo móvil. Este efecto de salto causaba una experiencia de usuario subóptima y una inconsistencia visual.
⚠ @midudev Tras horas de intentar solucionar este problema **pero con las devtools en modo móvil**, descubrí que se originaba por los estilos aplicados al scroll. Estos estilos no afectan al scrollbar global de la web (body), solo se aplican a los scrollbars del contenido, como por ejemplo el contenedor del menú de navegación. 
En el siguiente GIF, nota que los tamaños de los scrollbars son diferentes (body vs menu nav) y se produce el mismo efecto Layout Shift:
=> Fix: Add scrollbar-gutter to prevent layout shift on mobile mode

src/components/ColumnBoxers.astro, src/sections/Info.astro
Se agregó un pequeño padding a la section Info para corregir la superposición del logo de twitch con la bandera del boxeador.
https://github.com/midudev/la-velada-web-oficial/assets/78511737/c0c4299f-7265-4615-ad8a-0b72d9311b4b
https://github.com/midudev/la-velada-web-oficial/assets/78511737/632adbaf-53a8-4680-853e-8fe93aef2230
=> Refactor(Enhance Twitch Logo): Agregado un pequeño padding para corregir la superposición del logo.

CONTRIBUTING.md, src/components/BoxerBigImage.astro, src/sections/Countdown.astro, src/sections/SelectYourBoxer.astro
Errores al use `NodeListOf` and `NodeJS` types.
Problemas de linting.
1. Uso de `globalThis`
2. Importar componentes con `.astro`
3. Añadir `_` a variables no usadas por el momento ej: `name` -> `_name`.
4. Añadida entrada en [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md) (cuando esté mergeada, links de referencia abajo)
Evitar problemas de linting y hacer buen uso de las variables globales.
- [globalThis MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)
- [extendiendo window y globalThis Astro](https://docs.astro.build/en/guides/typescript/#extending-window-and-globalthis)
=> fix(#536): linting errors and imports

src/components/SectionTitle.astro
Se generalizo en un componente para los títulos de las secciones que se estaban duplicando el código del componente `<Typography />` .
Anteriormente, teníamos un problema de duplicación de código en el componente `<Typography />` al manejar títulos de secciones. Esta duplicación no solo era propensa a errores, sino que también dificultaba el mantenimiento y la coherencia en la apariencia de los títulos. Al generalizar el componente, hemos solucionado este problema y mejorado la estructura del código.
No inserte el componente, queda pendiente:
- Insertar en `components/Sponsors.astro` :
```tsx
--- 
import SectionTitle from "@/components/SectionTitle.astro"
--- 
<SectionTitle
title="Patrocinadores"
description="La Velada puede llevarse a cabo gracias a la colaboración de..."
/>
```
- …
=> feature: add SectionTitle Component

src/components/Header.astro
Arreglados errores de linter y formatter para poder commitear.
En pantallas de 1080p hasta que se oculta el navbar con los elementos, no era del todo responsivo.
Mejoras en la responsividad de `Header.astro`
1. Cambios de padding según tamaños de pantalla.
2. Errores de linter y formatter
Antes:
Después:
Mejorar la responsividad.
=> fix(Header): responsive navbar in small laptops (1080p)

src/components/BoxerDetailInfo.astro
Esto es una corrección para el component de BoxerDetailInfo ya que según el figma el color de los nombres de los boxeadores rivales eran del color --text-accent el color amarillo que predomina en la pagina.  Asi que he cambiado esa partecita. 
``` src/components/BoxerDetailInfo.astro ```
He modificado el código para cambiar el color del texto a text-accent cuando el título es "Rival/es", de acuerdo con la especificación del diseño en Figma.
**Antes de loscambios:**
**Después de los cambios:**
- [ ✔] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [✔ ] He revisado localmente los cambios para asegurarme de que …
=> fix: Color on BoxerDetailInfo title Rival/es

src/pages/boxers/[id].astro
En Movil la página se rompia el ancho por los iconos de las redes sociales
Ahora ya no se rompe la página
Agregado flex-row flex-wrap gap-8
Antes:
Ahora:
=> Fix: movil width de la página de cada boxeador 

src/layouts/Layout.astro
Añadido un link para saltar a `#main-content`.
Proporcionar soporte a las personas que solo puedan o tengan un teclado o similares para navegar.
1. Añadido `<a href="#main-content">`
2. Mostar el link solo al estar en `focus`.
Mejora de accesibilidad.
=> feat(Layout): accessibility feature, added skip to main content

src/components/ColumnBoxers.astro, src/consts/boxers.ts
Se corrige la orientacion de las fotos de los boxeadores en la seccion "Elige tu Luchador" para que su postura/fijacion de la foto sea orientada hacia el centro.
Se añade una clase de css que rota la foto del luchador si tiene el atributo en la interface Boxers que indica que debe ser rotada.
Antes:
Ahora:
Poco, ya que se usa un transform
=> fix: rotating photos correctly for symmetry

src/components/BoxerBigImage.astro, src/sections/SelectYourBoxer.astro
Permitir navegación al detalle del boxeador al dar click sobre su nombre desde la pantalla principal
Mejora de accesibilidad sin tener que moverse al icono pequeño para navegar al detalle del boxeador.
[x]. Se agrega link (tag a) para navegar hacia el detalle de cada boxeador
=> Permitir navegación al detalle del boxeador al dar click sobre su nombre

src/components/Velocimetro.astro
Actualmente esta apareciendo un error en la consola que dice **Uncaught TypeError: Cannot read properties of null (reading 'getContext')**
Cuando se redirige al detalle del boexador y luego se retorna a la página principal aparece el mensaje **Uncaught TypeError: Cannot read properties of null (reading 'getContext')**
=> Se válida que el elemento canvas exista dentro de la página

src/components/ButtonUp.astro
El botón de scroll top al iniciar la página funciona bien, pero a la hora de pasar a la página de algún luchador ya no aparece y a la hora de volver a la página inicial ya no vuelve a aparecer el botón. Issues #579
1- En el componente ButtonUp.astro se envolvió el código del script usando document.addEventListener("astro:page-load", () => {})
https://github.com/midudev/la-velada-web-oficial/assets/66286368/b0dbb215-cfc7-4671-beea-440d5de9cb8b
https://github.com/midudev/la-velada-web-oficial/assets/66286368/51536c03-96dc-4ead-b456-c80c8187d80e
Habría que revisar después si tiene impacto al usar document.addEventListener("astro:page-load", () => {}) en el rendimiento mientras se esté usando las viewsTransitions
-----
<a href="https://stackblitz.com/~/github.com/SubVray/la-velada-web-oficial/ …
=> Se arregló el botón scrolltop

src/components/Header.astro
Tenemos el siguiente codigo en el navbar el cual hace que se muestre el menu del header en el archivo `Header.astro`
```js
function toggleMenu(nav: HTMLElement | null) {
$("#menuMobileContent")?.classList.toggle("open")
nav?.classList.toggle("open")
document.body.classList.toggle("overflow-hidden")
}
```
Sin embargo cuando activamos el menu en modo mobile y re-escalamos la pagina con el menu activo esto hace que el menu desaparezca y luego la pagina no tenga scroll
Solucion, se añidio una clase adicional en esta funcion para que el scroll vuelva a su estado original despues de alcanzar el modo desktop y manteniendo el menu activo
`document.body.classList.toggle("lg:overflow-auto")`
=> :bug: fix: bug en el header cuando el navbar esta activo

src/components/BoxerSocialLink.astro
Se ha agregado una transisión al botón de las redes sociales del boxeador.
https://github.com/midudev/la-velada-web-oficial/assets/80859657/607a7f34-22fe-424c-b614-79a90559eb40
- [ x ] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [ x ] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ x ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
=> Add: Hover to boxer social link

src/components/BoxerDetailInfo.astro, src/pages/boxers/[id].astro
He añadido estilos para hacer la que la información del boxeador (en dispositivos móviles) se vea a bajo de la imagen.
No se podía observar correctamente la información del boxeador en dispositivos móviles.
He añadido estilos para hacer la que la información del boxeador (en dispositivos móviles) se vea a bajo de la imagen.
Antes:
Después:
=> Boxer Responsive Information

src/components/BoxerDetailInfo.astro, src/pages/boxers/[id].astro
Mejora la visualización en móvil de los detalles del boxeador, adaptandose al diseño que se encuentra en Figma.  
Antes:  
Después:
=> Mejora la visualización en móvil de los detalles del boxeador (Figma)

src/components/HamburgerButton.astro, src/components/Header.astro, src/consts/mobile-menu.ts
Mejorar la accesibilidad del menú de navegación mobile para usuarios que utilicen lectores de pantalla.
Anteriormente, los usuarios que utilizan lectores de pantalla no tenían forma de conocer el estado del menú de navegación, es decir, si este se encontraba en estado "expanded" o "collapsed". Además, el mensaje anunciado por el lector de pantalla cuando el botón del menú estaba en estado "focused" era poco descriptivo.
- Colocar un atributo `aria-label` mas descriptivo al botón.
- Agregar el atributo `aria-expanded`.
- Agregar el atributo `aria-controls` para identificar el elemento cuya presencia es controlada por estos botones.
- Modificar los atributos `aria-label` y `aria-expanded` ante un evento del tipo click sobre estos botones.
=> Improve accessibility on mobile menu

src/components/Velocimetro.astro
Modificación del medidor de pronosticos para que tenga coherencia con el diseño e imagen general de la web
Antes:
Después:
=> UI ux coherence pronostic design

src/sections/SelectYourBoxer.astro
imagen de boxerPhoto en la  seccion de SelectYourBoxer.astro no es clickeable para el usuario
cree un elemento anchor que envuelva la misma para que el la imagen pueda dirigir al usuario a la pagina del boxeador
cree una nueva etiqueta html  de tipo anchor en el script ubicado en archivo SelectYourBoxer.astro 
antes: 
https://github.com/midudev/la-velada-web-oficial/assets/122571870/1e9da55d-5b1a-43dc-a1af-c50eba15fa9a
despues: 
https://github.com/midudev/la-velada-web-oficial/assets/122571870/6e575b15-58e0-4243-80b2-aa29be1bf49f
- [👍 ] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [ 👍] He revisado …
=> add anchor link to boxer-image

src/components/Header.astro, src/components/LightsBackground.astro, src/components/NoiseBackground.astro, src/sections/Footer.astro
Alto uso de cpu a causa de usar innecesariamente la propiedad transition:persist de Astro.
Hace poco comence a tener problemas de rendimiento al abrir la pagina, me puse a revisar y me di cuenta que el mal uso de `transition:persist` aumenta muchisimo la carga a la cpu y en equipos de gama baja como es el mio se nota mucho la perdida de rendimiento.
Se elimina el `transition:persist` usado en el `header`, `footer`, `noise and lights background`, no es necesario usarlo en esos casos y solo empeora el rendimiento.
- Con `transition:persist` alcance a registrar uso del cpu hasta de 28%
- Sin `transition:persist` se registro como mucho un uso del cpu de 17%
=> Fix: reducir alto uso de cpu al navegar a causa del transition:persist

src/pages/boxers/[id].astro
Con el "y" se veía un poco mal para varios rivales, considerando que hay 10 boxeadores para El Rey de la Pista
Se cambió la **y** por una **/** para que cuando tenga más rivales el boxeador se vea bien
=> Formateo de rivales

src/function/miduCode.ts
Al utilizar el KonamiCode 'midu' cargan las imagenes en su tamaño original.
[Picture MiduDev](https://avatars.githubusercontent.com/u/1561955?v=4)
Al llamar la url de la imagenes de contributors se puede añadir el parametro '`size=` para indicar el tamaño de la imagen que queremos descargar.
[Picture MiduDev 150px](https://avatars.githubusercontent.com/u/1561955?v=4&size=150)
- Basandome en el tamaño que carga según el css 
```css
.bubbles {
width: 60px;
height: 60px;
}
#midu {
width: 150px;
height: 150px;
}
```
- Podriamos modificar la función que llama a las imagenes para que cargen el tamaño correcto
```js
const { avatar_url, login } = contributors[i]
const img = document.createElement("img")
// other things
img.classList.add("bubbles")
if (login === "midudev") {
img.setAttribute("id", …
```
=> FIX: Optimized images for KonamiCode 'midu'

src/components/AnimatedX.astro, src/sections/Countdown.astro
Luego de una viewTransition los elementos del dom cambian, por lo que hay que volver a recuperarlos con javascript, al no hacerlo se ejecuta todo el javascript pero con la referencia incorrecta a los elementos del dom, haciendo que no se vean las animaciones ni el countdown
issue #609 (bug logo animado y countdown)
. obtener los elementos del dom luego de una view transition
=> Fix countdown and animatedX after page:load (issue #609)

src/components/ForecastBoxer.astro, src/pages/boxers/[id].astro, src/sections/Forecasts.astro
Para mejorar la navegacion en el sitio web se agrego el anlace al boxeador correspondiente en la seccion de prediccion.
- Agregar etiqueta anchor al article de cada boxeador en la seccion de prediccion.
[before.webm](https://github.com/midudev/la-velada-web-oficial/assets/35277540/68e33978-ed36-4d79-8879-2327e83017c7)
[after.webm](https://github.com/midudev/la-velada-web-oficial/assets/35277540/b1daa54a-b6e1-45a8-86ed-abb3dc82b677)
=> feat: Add boxerHref prop to ForecastBoxer component to add anchor for the article

public/img/ui/left-arrow.svg, public/img/ui/right-arrow.svg, src/components/BoxerClips.astro
Agrega vista de Carousel en móvil a BoxerClips, adaptandose al diseño en Figma
En Figma:
Ahora:
Antes:
=> Feat: Boxer Clips Carousel (Figma)

src/components/BoxerDetailInfo.astro, src/components/BoxerDetailInfoRival.astro, src/pages/boxers/[id].astro
Para mejorar la accesibilidad según lighthouse, los elementos a los que se puede hacer focus deberían tener un id único.
Se aplicaba el id boxer-weight por defecto en página de detalle del boxeador.
Pasar por props ids correctos para cada detalle.
=> fix: focusable elements not unique 

src/components/BoxerSocialLink.astro
He añadido el hover del BoxerSocialLink como el de los sponsors de la home.
He añadido el hover del BoxerSocialLink como el de los sponsors de la home.
Antes:
Después:
=> BoxerSocialLink Hover

src/components/ColumnBoxers.astro
Se añadio una clase tailwind ( mb-2 ) que inserta margin bottom con el fin the resolver glith a la hora de seleccionar un boxeador.
Al momento de poner el cursor entre el margen de 2 boxeadores ocurre un glitch que alterna la imagen mostrada entre 2 boxeadores repetitivamente.
bastaria con añadir una clase que haga un poco de espacio entre la seleccion de boxeadores para que el cursor no ocacione el glicth.
< BEFORE > 
[before.webm](https://github.com/midudev/la-velada-web-oficial/assets/149793793/af1db7af-a407-458b-98c7-b085e8b57da2)
< AFTER >
[after.webm](https://github.com/midudev/la-velada-web-oficial/assets/149793793/643b0f25-b7d4-4b71-baec-bbba42d0f38e)
=> FIX: Add margin bottom to the .boxer-link

src/components/Header.astro
Agregar link a la home al logo del header y arreglar el height del logo ya que ocupaba bastante mas que el svg
Normalmente los logos en las webs mandan a la home y al menos en mi caso he intentando varias veces hacer click para volver a la home sin éxito, por lo que he agregado el link al logo
Agregar <a> al logo y agregar h-auto para evitar que el height del del svg se superponiese
=> Update HeroLogo link and height in Header component

src/components/ForecastBoxer.astro, src/sections/Forecasts.astro
Antes había un underline en el enlace entero (enlace con articulo, imagen, nombre y porcentage) que parecia que marcaba el porcentaje y quedaba poco intuitivo.
- Jugando con scale substituimos el efecto poco intuitivo y nos ahorramos algunas lineas de código.
- Agregado de aria-label
- Substituir `class:list` inecesarias por `class`
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/76450853/1042796f-33a4-40a7-b985-0aab9fcf54f5
Después:
https://github.com/midudev/la-velada-web-oficial/assets/76450853/88e781d4-3636-4084-b738-74a68af2d345
=> Pronostic boxers hover

src/pages/boxers/[id].astro
El diseño responsive de la web se estropea, específicamente en la página del boxeador.
Quitar el ancho de 800px a un div y en su lugar agregarle un ancho del 50%, evita que se estropee el diseño responsive.
En las siguientes screenshot se puede observar como el diseño responsive de la web se estropea
El problema en el navegador  Edge
El problema en el navegador  mozilla firefox
=> fix: responsive boxers page

src/sections/Footer.astro, src/sections/Info.astro, src/sections/SelectYourBoxer.astro
Se arregla el responsive para Z-Fold
Desborde de pantalla en mobile Z-Fold
Se agrega un max-w-[100vw] para que que el carrousel no desborde la pantalla, y se cambia el min width de los hr para que quede acorde.
Antes:
Después:
Mejora la compatibilidad de usuarios con mobiles con un width menor.
=> Se arregla el responsive para Z-Fold

src/sections/Combat.astro
Se estilizo el "vs" en los combates de la página de cada boxeador, para poder resaltar quienes se enfrentan y se bajo la opacidad del número de combate.
No se distinguía los nombres de los boxeadores.
Se utilizó el componente Typography para estilizar el texto.
=> Add: estilizar el vs de los combates

src/sections/SelectYourBoxer.astro
El issue #679 se origina debido a que no se esta removiendo el evento mouseenter después de hacer click en un boxeador.
Se creó una función controladora para poder reutilizarla en el addEventListener y removeEventListener del evento mouseenter y se agregó el evento astro:before-preparation para remover el mouseenter después de que el usuario haya cliqueado en un boxeador.
Issue #679
1. Crear una función controladora llamada handleMouseEnter
2. Añadir la función controladora en el addEventListener y removeEventListener del evento mouseenter
3. Agregar el evento astro:before-preparation
4. Ejecutar el removeEventListener del evento mouseenter dentro de astro:before-preparation
Antes:
[issue-boxer-selection.webm](https://github.com/midudev/la-velada-web-oficial/assets/164126437/2f703015-4c5b- …
=> Remove mouseenter event when clicking a boxer

src/function/miduCode.ts
Mostrar de forma aleatoria los contribuidores en el KonamiCode, Todos queremos ser robots !!! 🎊 
(Esto refleja a no mostrar siempre los mismo que están en el TOP con mas contribuciones)
Hacemos una petición a la API para obtener el número de paginas existentes de los contribuidores para luego hacer un random contribuidores por pagina.
=> show random contributors

src/sections/SelectYourBoxer.astro
Corrección en la funcionalidad para mostrar correctamente el "versus" o "aliada" del boxeador o boxeadora enfocada al cargar la página.
Al entrar a la página (sin importar que haya o no params) no se muestra el "versus" o "aliada" del boxeador o boxeadora  enfocada como se muestra en el video
Se ha añadido una comprobación del boxeador enfocado al cargar el js en la página, permitiendo así que se muestre correctamente el "versus" o "aliada" al cargar la página donde simplemente se recuperan los valores necesarios para reutilizar la función activateBoxer()
[demo-versus.webm](https://github.com/midudev/la-velada-web-oficial/assets/42650947/28c646e5-7ac4-429d-baf0-87d8551b5eea)
Funcionamiento esperado de la sección
=> Fix: view versus on initial page load

src/pages/boxers/[id].astro
Se hizo un filter de para poder mostrar los rivales de los boxeadores que participarán en El Rey de la Pista
No se mostraban los rivales de los boxeadores que participarán en El Rey de la Pista
Se hizo el filter sobre la constante boxers ( en minúsculas) y se comparo el id de boxeador
=> Filter de rivales de Rey de la Pista

src/pages/boxers/[id].astro
En la página de boxer, mostrar directament "Rival" o "Rivales" según la cantidad de oponentes en lugar de siempre mostrar "Rival/es".
=> show rival or rivals (prev rival/es) according to number

src/sections/SelectYourBoxer.astro
Cuando se hace resize del navegador y pasa a tamaño mobile el carousel de boxeadores no funciona como corresponde (no se activa el boxeador del medio)
Solo funciona de forma adecuada cuando el navegador parte con el tamaño mobile
Estaba al revés el observe el el eventListener change 
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/6934077/233316ec-88e1-461e-94ba-8ad5d6fd0348
Ahora:
https://github.com/midudev/la-velada-web-oficial/assets/6934077/4a1718ff-a04b-4e69-87a9-9e780222de97
=> Fix carousel observe when resize to mobile

src/pages/boxers/[id].astro
Si la **guardia** o el **alcance** del boxeador no existe, no se muestra. Se ha puesto un texto por defecto en esos casos
- Al ser **guard** y **reach** opcionales. 
```javascript
export interface Boxer {
guard?: string
reach?: number
// more code
``` 
- Podemos añadir un texto por defecto si no existen
```javascript
const guardBoxer = boxer.guard === undefined ? "Desconocida" : boxer.guard
const reachBoxer = boxer.reach === undefined ? "Desconocido" : boxer.reach
```
=> If not exist 'guard ' or 'reach' in Boxer, add default

src/function/miduCode.ts
-  Hay un problema con la solicitud de contribuciones al ejecutar el comando midu. El problema radica en que la solicitud no se está ejecutando de manera asíncrona como se espera.
- Mostrar al mismo tiempo la animación de los contribuidores con el audio de ibai
- Agregamos await en la respuesta del calculo de paginas que hace en la petición en la API de Github
- Se ha calculado el número total de contribuyentes por página en la solicitud, que asciende a 30. Este valor se divide por la duración del audio, que es de 1300 milisegundos (ms). El resultado de esta operación es de aproximadamente 433 ms. Para garantizar un ritmo adecuado, hemos redondeado este valor a 435 ms.
=> fix:konamiCode contributors request

src/components/Typography.astro
Se implementa el estilo de texto en minúsculas automáticamente para la familia tipográfica Atomic en el componente Typography.
La familia tipográfica Atomic no cuenta con caracteres en mayúsculas, por lo que cuando se utilizaba esta fuente en el componente Typography, era necesario escribir los textos en minúsculas o aplicar la función `toLowerCase()` para que se visualizaran correctamente.
Se agrega la clase de Tailwind `lowercase` en el objeto `variantClasses` cuando se utiliza la fuente Atomic en las variantes `"atomic-title"` o `"boxer-title"` del componente Typography. De esta manera, independientemente de si el texto se proporciona en mayúsculas, minúsculas o una combinación de ambas, se aplicará automáticamente el estilo de minúsculas para asegurar una representación correcta de la …
=> Aplicar lowercase a la fuente Atomic en el componente Typography

src/consts/sponsors.ts
Se removió tipos innecesarios en el archivo "sponsors.ts"
Ya que alguien había agregado los tipos en "types/Sponsors.ts",  así que importe esos tipos en "sponsors.ts".
=> remove types from Sponsors file

src/pages/combates/index.astro
He realizado una segunda versión de esta PR #688 de la página de combates quitando el Glow y adaptandolo mejor a lo que se esta usando en otras páginas tras lo comentado en el stream de hoy en Twitch
Me vine arriba y distaba mucho el diseño
Antes:
Ahora:
=> FIX: Improve combat page effects #688

src/components/ColumnBoxers.astro, src/sections/SelectYourBoxer.astro
Se elimina la lógica redundante utilizada para reseleccionar el boxeador actual (`?boxer=example` 🥊) al navegar de vuelta a la home 🏡.
Anteriormente, se estaba reseleccionando el boxeador actual cada vez que se regresaba a la home 🏡. Sin embargo, esto ya no es necesario, ya que la página se re-renderiza en el servidor con el boxeador seleccionado, evitando la necesidad de volver a hacerlo con JavaScript.
Se elimina el código innecesario para evitar reseleccionar el boxeador y prevenir posibles parpadeos de la informacion del  boxeador seleccionado entre navegaciones, tambien se agrega la logica al componente `ColumnBoxer.astro` para marcar los boxeadores como aliados y oponentes.
- Mejora la eficiencia al eliminar lógica redundante.
- Previene posibles parpadeos del boxeador actual entre …
=> Se elimina logica innecesaria al seleccionar el boxeador actual

src/pages/boxers/[id].astro, src/pages/combates/[id].astro
Se prerenderizan las rutas dynamicas en tiempo de build
Al usar `output: "server"` Astro no renderiza en build time las rutas dynamicas aunque se use el `getStaticPages()` si no que lo hace bajo demanda.
Se exporta una constante `export prerender = true` que habilita la prerenderizacion de las rutas dynamicas cuando usamos el `output: "server"`
- Alerta de Astro avisando que ignora el `getStaticPaths()` sin la solucion implementada
- La prerenderizacion de las rutas al habilitar la prerenderizacion
Esta solución mejora el rendimiento y la experiencia de usuario al prerrenderizar las rutas dinámicas en tiempo de build, evitando la renderización bajo demanda en el servidor.
https://docs.astro.build/en/basics/rendering-modes/#server-output-modes
=> Habilitar pre-renderizacion de las rutas dynamicas

src/components/Pronosticos/Vote.astro
Antes teníamos el mensaje de Ganador con un pseudoelemento, y eso suele dar problemas con los lectores de pantalla. 
El hover lo hemos hecho ahora de una forma distinta y además es accesible con el teclado.
Ahora tenemos un span en lugar del pseudoelemento y jugamos un poco con las propiedades group y group-hover y group-focus de TailwindCSS.
No afectan, es igual que antes.
No debería haberlos.
=> Hacer el mensaje de Ganador al hover (y ahora focus) accesible 

src/components/BoxerDetailInfoRival.astro
Se acomodó el alineado de rivales para la parte responsive
Se alineó a la derecha los rivales, ya que quedaban alineados al centro
**Antes:**
**Ahora:**
=> Fix format rivals

src/sections/SelectYourBoxer.astro
fixes #698
La animación de scroll horizontal en [SelectYourBoxer.astro](https://github.com/midudev/la-velada-web-oficial/blob/main/src/sections/SelectYourBoxer.astro) tenía algunas inconsistencias en la version móvil. Agregué un snap-mandatory y un event listener 'scroll' en el carouselInner para activarlos segun su posición en x.
Soluciona el issue [#698 Problema con el scroll de luchadores en la versión móvil](https://github.com/midudev/la-velada-web-oficial/issues/698)
* snap-mandatory para solucionar que la terminacion de la animacion de scroll termine en un elemento. Antes de esto la animacion hacia un salto al hacer un scroll largo.
* se agregó un scroll listener al carouselInner para comprobar la posicion en x de los elementos en el carousel. (Se aceptan futuras recomendaciones si …
=> fix: :lipstick: mobile boxers scroll animation

src/components/BoxerClips.astro
En el carrusel se muestran todas las frases al mismo tiempo, independientemente del tamaño de la pantalla, cuando lo deseado es mostrar solo una frase a la vez en pantallas pequeñas y permitir la navegación entre ellas usando las flechas.
El carrusel muestra todas las frases simultáneamente, en lugar de una sola a la vez en pantallas pequeñas con navegación por flechas.
Los cambios realizados permiten mostrar solo una frase a la vez en el carrusel en pantallas pequeñas, mientras que en pantallas más grandes se muestran todas las frases. La función updatePosition se encarga de actualizar la visibilidad de las frases según la posición actual y el tamaño de la pantalla.
Antes:
Después:
=> Error en Boxer Clips

src/pages/boxers/[id].astro
El alt de algunas banderas se muestra "Bandera de undefined".
- Buscamos el **countryName** segun el **country**  Ejemplo: {"es":"España}
```javascript
const countryName = COUNTRIES[boxer.country]
``` 
- Si el **countryName** no existe el **alt** sería 'Bandera de un país'
```javascript
const flagAlt = countryName === undefined ? "un país" : countryName.name
<BoxerBigImage id={id} name={boxer.name} country={boxer.country} countryName={flagAlt} />
``` 
- Lo soluciona de diferente manera #645
=> FIX: Atribute flags undefined

src/components/ColumnBoxers.astro, src/sections/SelectYourBoxer.astro
Se optimiza la carga de imágenes de los boxeadores en la página de inicio (home 🏡) dependiendo de si se accede directamente a ella o si se navega desde la página de un boxeador específico.
Cuando se navegaba desde la página de un boxeador hacia la página de inicio, las imágenes experimentaban un parpadeo debido al uso de lazy loading. Esto ocurría porque el DOM retrasaba la carga de las imágenes hasta determinar si estaban dentro del viewport, lo cual causaba un alto valor de Largest Contentful Paint (LCP).
Se agrega una condición para utilizar `loading=lazy` únicamente cuando se accede directamente a la página de inicio desde el navegador. Cuando se regresa a la página de inicio después de navegar hacia la página de un boxeador, se utiliza `loading=eager` para cargar las imágenes de …
=> Optimizando carga de imagenes dependiendo si se entra directamente a la home o se vuelve a ella

src/pages/combates/index.astro
Se arregla responsive para width <= 320px
Desborde del título en pantallas con un width <= 320px
Se agrega un query que modifica el font-size del título
Antes:
Después:
- [✔️] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [✔️] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [✔️] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [✔️] He actualizado la documentación, si corresponde.
Mejora la accesibilidad de usuarios con un width menor.
=> Se arregla desborde de pantalla

src/sections/SelectYourBoxer.astro
1. Debido a que el scroll de en las listas de boxeadores no es necesaria, se oculta
En Chrome se muestra una barra de scroll innecesaria en la sección `Elige tu luchador` en pantallas medianas
Pasos para reproducir:
1. Usar un width de pantalla comprendida entre el breakpoint de Tailwind `md` (momento en que se deja de mostrar el carousel) y la media query `width >= 1280` (momento en que se incrementa el tamaño de las imágenes de los boxeadores dispuestas en cada una de las 4 columnas). Por ejemplo, seleccionar el breakpoint `Tablet` de las Chrome Dev Tools
2. Scrollear hasta la sección `Elige tu luchador`
3. Hacer `hover` sobre cualquier boxeador de la última columna (Plex, Viruzz, Alana, Amablitz, Agustin y Guanyar)
1. Se oculta el scroll de la sección de boxeadores en pantallas mayores …
=> fix: prevent scrollbar on medium-size screens in boxers list

src/sections/SelectYourBoxer.astro
Se creó una función para actualizar la posición del thumbnail activo dentro del carousel de boxeadores en dispositivo móvil.
Al cargar la página, ingresando con una url que tenga el parámetro "boxer" (ejemplo: https://lavelada.es/?boxer=peldanyos) el thumbnail activo dentro del carousel no se estaba visualizando y no generaba una buena apreciación visual
1. Crear un función updateActiveThumbnailPosition para obtener la posición del thumbnail activo y actualizarla en el carousel para que pueda ser vista por el usuario.
2. Invocar la función solo en dispositivo móvil, ya que el carousel solo se visualiza en dicho escenario.
Before
After
- [ ✅] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas …
=> Update active thumbnail position in boxer carousel

src/pages/combates/[id].astro, src/sections/CombatFeatures.astro
Se añade la tabla de características 1vs1 en la página de combate según figma.
Se añade la tabla de características 1vs1 en la página de combate según figma.
Figma:
=> Tabla comparativa 1vs1 en página de combates

src/consts/boxers.ts
Los clips de [Skain ](https://lavelada.es/boxers/skain )y [unicornio](https://lavelada.es/boxers/unicornio) no están correctamente insertados. 
Al clicar el clip devuelve el error _La página consent.youtube.com ha rechazado la conexión._
Se ha utilizado el `embed` correcto para insertar los clips en la página
- Se ha actualizado los enlaces de los clips `embed` al formato correcto
```javascript
{
text: "Yo solo voy a decir que Karchez el año pasado de salvó, no diré nada mas",
url: "https://www.youtube.com/embed/k70W5W5UFjU?si=9JQt5c-yDe4uJUfL&amp;clip=UgkxlGr0lw1Xr65CkY4r_CfV18y4JuAVSL7y&amp;clipt=ELj7ORicxTo",
}
``` 
- Al insertar un clip deberia usarse la opción **Insertar** y no pegar el link del clip tal cual.
Stackoverflow: [La página ha rechazado la …
=> FIX Skain & Unicornio clips 'embed'

src/components/BoxerDetailInfo.astro, src/components/BoxerDetailInfoRival.astro, src/components/BoxerSocialLink.astro, src/pages/boxers/[id].astro
Nuevo diseño para la sección de los boxeadores arregle la vista para cuando es 2 contra 2 y cuando es el rey de la pista
y hice el ajustes tomando en cuenta los comentarios de la pull request #739 
* Muestra la foto del rival y se ve mejor la información del boxeador 
* Se arreglo la vista para el 2 vs 2 y el rey de la pista 
Nueva forma de visualizar a los rivales 
Ahora
* 1 vs 1
* 2 vs 2
* rey de la pista 
Antes 
* 1 vs 1
* 2 vs 2
* rey de la pista
- [ x] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ x] He …
=> Section details boxer

src/icons/tiktok.astro, src/icons/twitch.astro, src/icons/x.astro, src/icons/youtube.astro
En los dispositivos móviles, no se visualizan los iconos de las RRSS de los participantes de la velada con la misma altura.
Problema solucionado cambiando la altura del svg hasta la máxima que estos tenían (48px)
Problema solucionado cambiando la altura del svg hasta la máxima que estos tenían (48px)
Antes:
Después:
N/A
N/A
N/A
=> Cambio altura de iconos para buena visualización en dispositivo móvil

src/sections/Combat.astro
Se agrega la imagen del titulo de combate de la pagina `/combates/[id].astro` como fondo detras de los peleadores (`zeling x nissaxter vs alana x amablitz`). Anteriormente se tenia el numero del combate.
Detras del texto de los peleadores (`el mariana vs yosoyplex` o `el rey de la pista`) teniamos el numero de combate en grande con la fuente Atomic, lo que se veia bien pero ya era algo que teniamos en el titulo superior y era algo simple.
Se agrega la imagen de titulo de combate que esta en la pagina `/combates/[id].astro` en el fondo de los peleadores junto con el transition:name para que se haga una transition al navegar y se deja como fallback el numero de combate que estaba anteriormente.
- Antes
- Despues
[demo](https://github.com/midudev/la-velada-web-oficial/assets/93395794/39667382 …
=> Se agrega la imagen de titulo de combate como fondo detras de los peleadores

src/components/Combates/BackgroundVideo.astro, src/pages/combates/[id].astro
Se movio el video de fondo a un componente y se agrego dentro del la etiqueta layout `combates/[id].astro`, ya que al estar por fuera, estaba renderizando los meta tags en el body.
- Ahora se renderizan los tags en el head.
- Soluciona problemas de semantica y Seo.
- Se creo un componente backgroundVideo.astro
- Se movio dentro del layout en la pagina `combates/[id].astro` el video.
**Antes.**
**Ahora**
=>  Fix: Meta Tags Rendered in the Body Instead of the Head (Combatates/[id].astro)

src/consts/combats.ts, src/consts/forecasts.ts, src/types/Combat.ts
Se removió código innecesario y se actualizó el tipo Combat
Código duplicado
- Se removió el tipo `Forecast` en `consts/forecasts`, en su lugar se importó dicho tipo desde `types/Forecast`
- Se actualizó el tipo `Combat` en `types/Combat`
- Se removió el tipo `Combat` en `consts/combats`, y en su lugar se importó dicho tipo desde `types/Combat`
=> Remove unnecessary code

src/components/BoxerDetailInfoRival.astro
nuevo fondo para los rivales en la pagina de los detalles del boxeador
color los mismos estilos que en el seleccionar boxeador de la pagina del home
cambiar el fondo del rival para el 1 vs 1 y 2 vs 2
Ahora 
1 vs 1
2 vs 2 
Antes 
1 vs 1
2 vs 2
- [ x] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [ x] He actualizado la documentación, si corresponde.
unificar la selección de …
=> new bg rival

src/components/Boxers/Gallery.astro
Dentro del componente Boxers/Gallery, he modificado el manejador de evento click para los links. 
Solución del issue #801. 
Antes se mostraba primero el lightbox y luego se actualizaba la imagen, provocando un ligero retardo. Ahora se actualiza la imagen antes de mostar el lightbox, de esta manera se elimina el problema.
[Grabación de pantalla desde 30-03-24 18:11:42.webm](https://github.com/midudev/la-velada-web-oficial/assets/98945796/3934b606-ab6c-4f24-9a2e-93183c05b04c)
[Grabación de pantalla desde 30-03-24 18:13:12.webm](https://github.com/midudev/la-velada-web-oficial/assets/98945796/49d474fb-9e79-40f1-aa94-2f12acf3bdc0)
=> \#801 Arreglo de retardo  de la imagen al abrir el lightbox de la galería de los boxeadores

src/sections/CombatFeatures.astro
Se ha cambiado un poco la tonalidad de color de la tabla en combates, un poco mas oscura para que al leer no moleste tanto el video de fondo.
Ahora es un poco mas cómoda la lectura de la tabla, las luces y colores del video no afectan
Antes
Ahora
=> Estilos de tabla de características de los combates

package.json
Añadidos tipos para la `View Transition API`
Error de tipado cuando se usaba `View Transition API`
1. Añadida dependencia de desarrollo `@types/dom-view-transitions`
Antes:
> [!important]
> ERROR: Property 'startViewTransition' does not exist on type 'Document'
Después:
Mejoras para los desarrolladores.
=> feat(types): added view transition types

src/consts/combats.ts
He corregido la orientación de las fotos de los boxeadores en la página pronósticos. Antes en algunos combates se daban la espalda, tras los cambios esto ya no sucede.
Issue #818.
He modificado el orden de los boxeadores en el campo ```boxers``` de la constante ```COMBATS```.
Tras revisar los archivos donde se usa la constante ```COMBATS```, no he identificado ningún conflicto con el nuevo de orden de los boxeadores.
=> Corrección de la orientación de las fotos de los boxeadores en pronósticos

src/components/ColumnBoxers.astro
Añadida una animación a la propiedad `scale` para que cuando se haga hover en los elementos del `nav` se anime al igual que el resto de properties.
* Añadida la propiedad CSS `transition` en todos los lugares donde se hacía un escalado de imagen en un `boxer-link`.
* El único problema que he encontrado es que como la clase `active`, `.oponent` y `.ally` se eliminan usando JS, la animación sólo se produce en entrada y no en salida. Estoy intentando ver cómo arreglarlo sin duplicar mucho código (he probado con `.addEventListener("transitionend", callback)` en el JS pero no funciona 🤔 .
=> Added animation to `scale` property of the boxer when hovering

src/components/BoxerSocialLink.astro, src/pages/boxers/[id].astro
He corregido la manera en la que se visualizan las redes sociales en la página de cada boxeador en móvil. Debido que al estar estiradas al ancho de la pantalla de móvil no se visualizaba correctamente, ahora se logran visualizar de una mejor manera con una grilla.
Visualización de las redes sociales en la página de cada boxeador en móvil.
He cambiado los estilos del div que contiene los enlaces de cada red social para que se muestre en una grilla en móvil, sin perder las características en otras pantallas. Y a su vez un centrado a la ultima red social.
Antes:
Después:
Una vez revisado los archivos, se ha detectado que no presenta cambios de rendimiento ni afecta a ningún otro código.
=> fix: social networks in fighters on a mobile screen

src/components/Pronosticos/Vote.astro
Arreglo del scrollIntoView, al votar en el combate de rey de la pista. También he añadido que no haga el scroll si el siguiente combate ya está votado, evitando scrolls que pueden ser no deseados para el usuario.
Issue #823 y propuesta para evitar scrolls potencialmente inedecuados
He añadido la clase king-team a los boxeadores del rey de la pista, al hacer el scrollIntoView, para ellos se usa al abuelo en vez de al padre para conseguir el siguiente comabte. Además, he añadido las clases not-completed y completed a las etiquetas ```<li>``` que contienen los combates. De esta manera, se tiene un control sobre los combates votados y se evita hacer scroll hacia ellos.
[votos-antes.webm](https://github.com/midudev/la-velada-web-oficial/assets/98945796/71acc5cb-1d0e-402b-b5fc-9bdeda05618d) …
=> Arreglo y mejoras en scrollIntoView de las votaciones

src/consts/boxers.ts
Se han acortado y arreglado los links de las redes sociales de los boxeadores.
-El link al Twitter de Zeling redireccionaba a una cuenta incorrecta.
-Se han acortado los links de las redes sociales.
-El link al Twitter de Zeling ha sido sustituido por el real.
-Se han eliminado los subdominios (m/www), los parametros (lang/view_as) y los paths innecesarios.
-Los IDs de Youtube han sido cambiados por el nombre de usuario para ser más legibles y cortos.
=> Fixed and shortened boxer's social media links

src/consts/boxers.ts
Se han arreglado faltas de ortográfia en las citas de los boxeadores.
-Arreglado el issue (https://github.com/midudev/la-velada-web-oficial/issues/826)
-Arregladas tildes y falta de ortografía.
Añadidas/Eliminadas las tildes correspondientes, typo y el nombre de "xokas".
https://github.com/midudev/la-velada-web-oficial/issues/826
=> Fix (#826) and other boxers quotes typos

src/consts/boxers.ts
Luzu tiene un podcast sobre la Velada y a confirmado el peso de Nissaxter
Actualizar peso de Nissaxter
Cambiar peso a 45kg
-  [Video de Luzu](https://youtu.be/h5Ptj-rfnM8?si=gE4B83eoOi6VJ1E8&t=316)
=> Update weight of Nissaxter

src/pages/404.astro, src/pages/boxers/[id].astro, src/pages/combates/[id].astro, src/pages/combates/index.astro, src/pages/legal-advice.astro, src/pages/privacy-policy.astro, src/pages/pronosticos.astro
Se han actualizado los títulos de las páginas para mantener el mismo estilo/formato.
Mantener el mismo formato en todos los títulos de las páginas.
Cambiar los títulos de las páginas siguiendo el siguiente formato: '{titulo de la página} - La Velada del Año IV'
=> Update page titles

src/utils/seoConfig.ts
Algunas de las imágenes borradas del proyecto siguen con la ruta relativa en el archivo `seoConfig.ts` y se siguen llamando en la página
Se han actualizado el link de las imágenes según la url del cdn
```typescript
screenshots: [
{
src: "/img/screenshots/desktop_1.jpg",
type: "image/jpeg",
sizes: "1024x964",
form_factor: "wide",
},
``` 
```typescript
screenshots: [
{
src: "https://cdn.lavelada.dev/screenshots/desktop_1.jpg", // modicada
type: "image/jpeg",
sizes: "1024x964",
form_factor: "wide",
},
```
=> FIX Screenshots images from SEO (not found)

src/components/Combates/BackgroundVideo.astro
El vídeo corto del combate no se reproducía en la carga inicial de `lavelada.es/combates/[id]`
#848
1. Añadir un evento `astro:page-load` reproducir el vídeo si está y sino eliminar el evento.
Todas las pruebas necesarias están en #848
Mejorar la experiencia de usuario de las personas que usan Safari
=> fix(#848): Combat background video not playing on Safari

src/components/ClipsModal.astro
Una animación simple al abrir ClipsModal
- Se agrego un `keyframes` al `backdrop` que genera un cambio en el `background-color` durante 200ms
https://github.com/midudev/la-velada-web-oficial/assets/61036343/f47e2492-e289-46c7-86e8-d79c5351c66a
Se que no se ve la bandera ya que el asset por lo visto funciona con `src/middleware.ts` el cual tuve que deshabilitar para poder ejecutar el entorno de desarrollo.
=> Added animation when opening ClipsModal

src/components/CalendarButton.astro
Arreglo el ancho del botón de "agregar al calendario" para que el texto dentro no haga un salto de línea (el salto de línea lo hace cuando la ventana tiene un ancho de 768px a 782px)
cambio la clase w-full por w-max
Antes:
Después:
=> fix width calendar button

src/sections/PresentationVideo.astro
El glow del background en `PresentationVideo` se cortaba con la introducción del banner de **Revolut**.
Deja de haber un corte visible en después del banner de **Revolut**.
1. Aumentar el `padding-top` de `5rem` a `8rem`.
Antes:
Después:
Hacer una UI más limpia.
=> fix(PresentationVideo): glow effect no longer cuts off

src/components/ClipsModal.astro
Una modificación mínima para permitir que el `iframe` se vea mejor en móvil
El `iframe` se salía de la pantalla en móvil
- Se cambio de `px` a `viewport` al contenedor del `iframe` para que sea mas legible en móvil
https://github.com/midudev/la-velada-web-oficial/assets/61036343/c10beba6-a183-4496-9f39-46e970336915
=> fix: mobile view of modal in ClipsModal

src/components/Pronosticos/Vote.astro
No se mostraba los nombres de las boxeadoras unidos por un `y` siendo equipo.
Closes #853
1. Añadido separador `y` entre ambas boxeadoras.
2. Juntado el nombre de `ama-blitz` para que aparezca como `amablitz`.
Antes:
Después:
Mejorar la experiencia del usuario con la mejora de la legibilidad de los equipos.
#853 
=> fix(#853): added separators to team boxer votes text

src/components/Pronosticos/Vote.astro
Se mejora la experiencia de usuario añadiendo `title` en los `<button>`.
Si hacías hover no te describía qué hacía el botón.
En la renderización del HTML, se mostraba la función de los separadores.
1. Añadir `title` a los `<button>` de `Vote.astro`.
2. Llamar a la función para hacer la separación de los nombres.
Antes:
Después:
Mejora de la experiencia de usuario.
=> feat(Vote): added `title` and improved `alt`

src/components/Pronosticos/Vote.astro
Se añade espacio a los boxeadores como `la-cobra` -> `la cobra` y se dejan sin espacio boxeadores como `agustin-51` -> `agustin51`.
No había separación para los nombres como `La Cobra` o `El Mariana`. Ahora sí.
1. Reemplazar `-` por espacio si no es `agustin-51`.
Antes:
Después:
Ajustar acorde con los nombres de los participantes.
=> fix(Vote): proper separations for boxer's names

src/components/HamburgerButton.astro, src/components/KonamiCode.astro, src/lib/dom-selector.ts
Simplemente he añadido [tipos genéricos](https://www.typescriptlang.org/docs/handbook/2/generics.html) a la librería dom-selector y solucionar algunos errores de tipos con respecto a la implementación anterior.
Este cambio hace que el uso de $ y $$ sea más claro, corto y ayude al manejo de gestión de errores (por que antes en $ no avisaba de un caso `null`):
```typescript
// antes
const element = $("#my-id") as HTMLDivElement
const elements = $$(".my-class") as globalThis.NodeListOf<HTMLDivElement>
// después
const element = $<HTMLDivElement>("#my-id")!
const elements = $$<HTMLDivElement>(".my-class")
```
- Tipos genéricos: https://www.typescriptlang.org/docs/handbook/2/generics.html
=> Generic types in the dom-selector library

src/sections/PrincipalDate.astro
Desde cualquier sección de la web, por ejemplo "https://lavelada.es/combates", si vuelves a la pantalla principal desaparece la fecha del evento.
El problema esta en "src\sections\PrincipalDate.astro" en la linea 165 "document.addEventListener("DOMContentLoaded", main)" el cual solo se carga 1 vez al entrar a la web.
He cambiado el "DOMContentLoaded" por el "astro:page-load" para que se ejecute dicha función siempre que se cargue una página de la web.
ANTES
DESPUES
- [X ] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [X ] He revisado localmente los cambios para asegurarme de que no haya errores ni …
=> fix/Date not loading after redirecting to PrincipalDate page

src/pages/combates/[id].astro
En la página de combates, las imágenes de los boxeadores superponen parte del header y de la sección de características, afectando la visibilidad y el diseño de la página.
Soluciona el problema de superposición visual en la página de combates donde las imágenes de los boxeadores interfieren con otras secciones.
Afectaba a la visibilidad del botón hamburguesa (del menú) en dispositivos móviles haciendo imposible verlo y usarlo, la etiqueta "vendidas" de Entradas en ordenadores y texto de la sección de características de los boxeadores.
He agregado un z-index de -10 al div de imágenes de los boxeadores para prevenir que estas sobresalgan sobre el header.
Esta solución no afecta a otros componentes de la interfaz al cambiar la superposición.
**ANTES**
**DESPUÉS**
=> Corrección de la superposición del div de boxeadores sobre el menú y las secciones

src/components/BoxerDetailInfoRival.astro
Se arregla un problema el cual ocurría en el path "/boxers/[id]", cuando la ruta terminaba en "/" (ejemplo: /boxers/sezar-blue/" y se seleccionaba algún rival, este redireccionaba de manera errónea debido al "/" al final (ejemplo: /boxers/sezar-blue/skain).
Los indexadores como Google hacen que la página por defecto al final de la URL utilice "/", por lo que puede dañar la experiencia de usuario.
No encontré una issue relacionada. Fue por experiencia propia al buscar "Sezar blue velada 4" en el buscador de Google que encontré el bug.
El cambio propuesto consiste en utilizar una ruta absoluta (/boxers/[id]`) en el href de los enlaces de los rivales, en vez de una ruta relativa ([id]).
En la siguiente captura se ve el problema cuando la ruta termina en "/":
Acá solucionado:
N/A
N/A
- …
=> fix: fixed /boxers/[id]/ -> /boxers/[id]/[id]

.github/workflows/tag-conflicts.yml
Related to #943
Corrects spelling errors in `.github/workflows/tag-conflicts.yml`.
- Updates the `commentOnDirty` message to correctly spell "resuélvelos" instead of "resuelvelos".
- Updates the `commentOnClean` message to correctly spell "resueltos" instead of "resuletos".
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/midudev/la-velada-web-oficial/issues/943?shareId=3f6cf96c-201f-4868-bbff-223c5bff4abe).
=> Fix spelling errors in conflict comments

src/pages/api/votes/[combatId].ts
A malicious user could do a call to `POST /api/votes/<combatId>` endpoint passing an arbitrary boxer id, i.e voting `guanyar` in `1-agustin-51-vs-carreraaa` combat.
To mitigate this issue, we can implement filtering on the `voteId` from combat boxers' IDs. This would prevent the submission or voting of any arbitrary boxer ID that isn't associated with the specified combat.
Fix bug when passing an unrelated boxer id as a `voteId` to `POST /api/votes/<combatId>` endpoint. 
Filter `voteId` from combat boxers ids to prevent passing or voting an arbitrary boxer id not related to the given combat
=> Fix bug when passing an unrelated boxer id as a voteId to `POST /api/votes/<combatId>` endpoint

src/pages/api/votes/[combatId].ts
Al hacer click en el combate 2v2 en <https://lavelada.es/pronosticos>. Se producía un error por el filtrado, introducido en la PR #947, a la hora de hacer `POST /api/votes/<combatId>`.
Fixes #951 
1. Mantener filtrado si no es 2v2
2. Si es 2v2, ver si el boxeador a filtrar se encuentra en `voteId`.
https://github.com/midudev/la-velada-web-oficial/assets/71392160/26130211-c29e-427c-a04b-27f91a20ca10
=> fix(#951): fixed `voteId` filtering for `POST /api/votes/<combatId>`

src/components/Header.astro
Se ha implementado una validación para permitir que, cuando los usuarios estén dentro de los combates, la línea del encabezado pueda ocultarse, ya que se considera que la visualización es más adecuada sin ella en ese contexto específico.
Al implementar esta validación, se espera mejorar la apreciación visual del contenido gráfico.
=> Eliminate the header line in the internal of the combats

src/consts/boxers.ts
Agregar el entrenamiento de Nissaxter.
Miniatura: 
Drive con la miniatura en formato webp: https://drive.google.com/drive/folders/1UKWS1KHgytcKuMboV1gpPkw8NtI9-CQi?usp=sharing
- Código de referencia: 
Video de youtube: https://youtu.be/zqatWGonjt4?si=Vl6aQBd0ciVn4s6B
=> Añadiendo entrenamiento de Nissaxter

src/consts/boxers.ts
Se ha cambiado la id del vídeo de la Cobra
Minuatura: 
Link del video: https://www.youtube.com/watch?v=HFR0F2G71y4
=> Actualizar entrenamiento de La Cobra

src/consts/boxers.ts
Agregar entrenamiento de Will con los datos al archivos boxers.
Miniatura:
- Código de referencia: 
Video de youtube: https://www.youtube.com/watch?v=GWLZSfJsSCo&ab_channel=MisterFactous
=> Añadir entrenamiento Will

src/components/BoxerBigImage.astro, src/components/BoxerDetailInfoRival.astro
He añadido `z-index` a la imagen principal y a la de los rivales.
Closes #842
1. Añadir `z-index` por superposición de imagen sobre imagen
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/287a0486-37e3-47d0-8113-ddfc322d1a50
Después:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/78169000-d83e-47de-bafe-8bc995e591e9
Mejorar la experiencia del usuario
=> fix(#842): boxer rivals' hover blink

src/layouts/Layout.astro
Se usa la media query hover @media (hover: hover) para evitar que el custom scrollbar solo sea visible en dispositivos cuyo mecanismo de entrada primario del usuario puede flotar sobre los elementos.
Soluciona el desplazamiento de los elementos en el menú movíl y la visualización del custom scrollbar.
Antes (Brave):
Antes (Edge/Chrome):
Después:
Experiencia de usuario.
Es una solución provisional ya que es un bug de CSS introducido junto a las propiedades scrollbar-width y scrollbar-color en los navegadores que soportan ::-webkit-scrollbar.
El principal problema es que en algunos navegadores se muestra el custom scrollbar y en otros no se muestra, pero ocupa el espacio.
Por ahora no hay mucha información al respecto.
=> fix: custom scrollbar visible on mobile

src/components/BoxerClips.astro
Se hace visible el `overflow-x` del section que contiene los textos de los clips de los boxeadores en desktop, para evitar que el texto se corte al hacer `:hover` e incluso sin hacer `:hover` en algunos casos; En mobile se mantiene ya que tiene sentido 🤓.
Antes: 
Después:
=> fix: boxer clips text overflow hidden on desktop

src/components/LightsBackground.astro, src/components/NoiseBackground.astro
Se hace que el background no se reposicione en los dispositivos con viewport dinámico.
Se da altura explicita de `100vh` a los elementos parte del background (Noise and Lights)
Estado inicial:
Al hacer scroll (Antes):
Al hacer scroll (Despúes):
=> fix: background (noise and lights) with dvh

src/components/ForecastBoxer.astro
Se corrige contenido cortado en el componente `ForecastBoxer`
Se remueve el `overflow-hidden` del `wrapper` para evitar que se corte el contenido que sobresale o que puede llegar a sobresalir, en este caso, el nombre del boxeador y el porcentaje. El `overflow-hidden` se usaba para mantener el `aspect-ratio` de la imagen del boxeador, ya que la imagen crecía con el contenido. Para solucionar esto, se usa `absolute` en el contenedor del título y porcentaje, posicionándolo debajo y al centro de la imagen, y se agrega al `wrapper` un `pb-[content-height]`. De esta manera, al "no tener" el contenido en el `wrapper`, la imagen mantiene su aspect ratio y el contenido no se corta.
Antes:
Después:
=> fix: ForecastBoxer texts overflow

src/components/Boxers/Gallery.astro
Como se menciona en #918, al hacer la actualización de imágenes en `Gallery.astro` se utiliza `View Transitions API` lo cual genera que las imágenes que tienen una transición actúen.
Fixes #918
https://github.com/midudev/la-velada-web-oficial/blob/873a47fd8c88e58711143b0f1a8ad0487cb30a8f/src/components/Boxers/Gallery.astro#L188-L196
1. Eliminar la transición usando `View Transitions API`
```diff
- if ($lightbox.open && document.startViewTransition) {
-   document.startViewTransition(() => {
-     updateImg(link)
-   })
-  return
- } else {
+ if ($lightbox.open) {
updateImg(link)
}
```
Antes:
https://github.com/midudev/la-velada-web-oficial/assets/71392160/1fcb8699-aa24-4a4e-aa80-7471162a300b
> [!NOTE]
>
> En #918 se explica más en detalle el parpadeo en cuestión.
Después: …
=> fix(Gallery): boxer images flickering when updating gallery

src/components/Pronosticos/Vote.astro, src/sections/Combat.astro
Las imágenes en la sección de `Pronósticos` en dispositivos móviles, no correspondían con el diseño general de `Combates` o `Pronósticos` en dispositivos de escritorio.
Incluir `mask-image` en las imágenes.
1. Añadir `style="mask-image: ..."` a los componentes `Image`.
- Antes:
- Después:
Mejorar la coherencia en la UI.
=> fix(pronósticos): images in mobile with no `mask-image`

src/components/Hero.astro
Se ha actualizado la edición del evento de "La Velada" de la 4 a la 5 en el h1 de la página principal.
La web aún mencionaba "La Velada 4" en lugar de "La Velada 5", lo que puede afectar al SEO
- Se ha actualizado el texto del h1 donde se hacía referencia a "La Velada 4" por "La Velada 5"
Mejora del SEO
- Documentación del proyecto:
=> Update event edition from La Velada 4 to La Velada 5 in h1

.vscode/settings.json, .vscode/tailwindcss.json
To avoid warnings in CSS files when using TailwindCSS's built-in functions or directives, they have been added to VS Code so that they are properly recognized.
=> Add references to TailwindCSS Functions and Directives to VS Code

src/styles/global.css
It extracts the most suitable colors from the original La Velada del Año V flyer and defines them in OKLCH format within the global styles, enabling seamless manipulation by Tailwind CSS.
=> Add custom colors to global styles based on La Velada del Año V color palette

src/components/BoxerCard.astro
Mejora las tarjetas de boxeadores con efectos visuales como escala y bordes brillantes, animación de brillo en hover y transiciones más suaves (movimiento reducido)
Mejora de la UX/UI
https://github.com/user-attachments/assets/1b0f94d6-5700-495d-a8a5-5811ce7bc1fb
https://github.com/user-attachments/assets/57078a59-b30a-4112-8d18-2842f3316d5e
=> Mejora de las tarjetas de boxeadores con efectos visuales

src/components/Sponsors.astro
=> Responsive Sponsor layout: based on screen width

.prettierignore, .prettierrc, package.json, pnpm-lock.yaml
This PR adds the Prettier configuration based on the config from the Lolalolita Land website, using the Astro and Tailwind plugins to enhance code formatting and ensure consistency. It also includes a `.prettierignore` file and a `pnpm format` command for formatting the code.
=> ADD Prettier config ,ignore, and comand in package.json 

src/components/Hero.astro
Add an entrance animation to the boxer cards for a smoother loading and to match the logo animation style.
Before:
https://github.com/user-attachments/assets/f04869e0-557a-4033-9941-167f88d4e856
After:
https://github.com/user-attachments/assets/7670b6bb-6281-4e8c-8ab7-1a4ca93a7d29
NOTE: If it looks lag, it's not the animation, it's my screen recorder. 🥲
=> feature: boxer cards entrance animation

src/components/BoxerCard.astro
Al hacer hover sobre un boxeador, los demás boxeadores pasan a escala de grises excepto su rival.
=> Emparejamiento de boxeadores

src/consts/pageTitles.ts, src/pages/combates/[id].astro
In the `combates` page, I updated the Title adding the name of the two selected fighters and following the structure of the project.
=> feat:Title in 'combates' updated with dynamic fighters

src/components/Footer.astro
When opening the page on bigger screens, the footer image disappeared as it grew. This issue was particularly evident on 2xl screens.
To address this problem, the following changes were implemented:
1. Replaced `height` with `min-height` to allow the footer image to grow appropriately.
2. Added padding and margin specifically for 2xl screens where the issue was most noticeable.
These changes ensure that the footer image remains visible and properly sized when scaling to bigger screens, improving the overall responsiveness of the footer component.
=> fix(footer): improve responsiveness for larger screens

src/components/Header.astro, src/pages/combates/index.astro
Se actualizó el header para que el logo sea visible en la pantalla de combates, manteniendo una navegación consistente a la página principal.
- Se eliminó la imagen del logo en combates/index.astro para evitar que apareciera repetida.
- Ahora el header mantiene la misma estructura en todas las páginas.
Antes:
Despues:
=> Fix: Se muestra el logo en la pantalla de combates para mantener coherencia con el header

src/components/BoxerCard.astro
Se corrigió un error de tipado en la variable timeoutId, ya que setTimeout en entornos como Node.js devuelve un objeto Timeout, mientras que en navegadores devuelve un number. 
La solución fue cambiar:
**Antes:**
```ts
let timeoutId: number | null = null;
```
Esto generaba el error:
> El tipo 'Timeout' no se puede asignar al tipo 'number'.
**Después:**
```ts
let timeoutId: ReturnType<typeof setTimeout> | null = null;
```
Este cambio asegura que `timeoutId` tenga el tipo correcto en cualquier entorno, evitando errores de asignación.
=> Fix timeout id card type

src/components/FighterSelector.astro
Se corrige el error de tipo y se asegura que las clases se apliquen correctamente formateado en string
**Antes**:
**Después:**
=> Fix selector fighter type class

src/components/Hero.astro
Se ha cambiado el z index de algunos textos del hero para que no queden por encima del header,
Antes:
Después:
=> fix: texts on Hero z index decreased

src/components/Hero.astro
Se arreglo el margen inferior del banner informativo de Twitch. En algunas pantallas (incluida la mía) la mitad del banner esta oculto y no se logra ver todo el texto a menos de que se haga un "zoom out"
=> Ajuste del margen inferior en el banner informativo de twitch

src/components/LiteYouTube.astro
Se Implementó una mejora en la gestión del botón de reproducción para lite-youtube que elimina la necesidad de cargar dos versiones del mismo SVG, reduciendo así el tamaño del CSS y mejorando el rendimiento.
=> [FEATURE] Optimization of the play button in lite-youtube

src/pages/combates/index.astro
Se cambio grid por flex para mostrar el último combate centrado, creo es más estético, se comprobó en Desktop
=> Mostrar los combates con Flex centrando el último

src/pages/combates/[id].astro
Se ha corregido el comportamiento al acceder a combates inexistentes. Antes, si el nombre del combate no coincidía, se mostraban datos sin sentido. Ahora, si el combate no existe, se redirige automáticamente a la página 404.
- Se valida si el nombre del combate existe.
- Si no existe, se redirige a la página 404.
Es la misma validación que se realiza en luchadores, pero en combates no estaba implementado.
Accede a un combate válido: http://localhost:4321/combates/1-peereira-vs-rivaldios
Accede a un combate inexistente: http://localhost:4321/combates/1-peereira-vs-rivaldiossbhdbsj
Resultado esperado: Debe redirigir a la página 404.
=> Añadir redirección a la página 404 si no se encuentra el combate

src/pages/combates/index.astro
El tamaño de letra de la vista de combate se sobre sale en la vista del movil, para ello se agrego una linea de codigo para cambiar el tamaño de letra según el ancho de pantalla usando tailwind.
Antes:
Después:
=> fix: adjust the font size of the bout list header for mobile devices

src/components/BoxerCard.astro
Se ha eliminado el código que hacía la navegación vía js.
Funciona la view transition entre `/` y `/luchador/[id]`
fixes #1246
=> fix view transition by removing addEventListener click on singleBoxerCard

src/consts/fighters.ts
Se han agregado nuevos clips a los luchadores Perxitaa y Gaspi en el archivo consts/fighters.ts. Cada clip incluye una frase destacada y el enlace correspondiente a YouTube, con el momento exacto en el que se menciona.
Este cambio sigue la misma estructura implementada anteriormente con Peereira y Rivaldios, mejorando la información disponible de cada luchador y permitiendo que los usuarios accedan fácilmente a fragmentos clave de sus declaraciones.
=> feat: agregar clips de Perxitaa y Gaspi con frases destacadas

src/consts/fighters.ts
Esta PR agrega nuevos clips al array clips de los luchadores Andoni y Carlos Belcast en el archivo consts/fighters.ts.
Cada clip contiene una frase representativa del luchador y un enlace a YouTube que lleva directamente al momento exacto en que se dice.
Estos cambios continúan con la mejora del contenido audiovisual en los perfiles de los luchadores, destacando momentos importantes para los fans.
=> feat: agregar clips para Andoni y Carlos Belcast

src/pages/combates/index.astro
Hola Midu que tal como estas, espero que bien. Esta PR da una mejor animación en la pagina de combates se usaron la animaciones de tu plugin de tailwind y se uso el la "number" propiedad para hacer este efecto. Espero te guste
Antes: 
https://github.com/user-attachments/assets/944ffe0d-e654-4f59-8978-e0753bb60dbb
despues:
https://github.com/user-attachments/assets/58b1dc43-69a3-420e-b40a-02ba513c3b93
Nota: GitHub solo me deja subir videos de 6 segundos, por eso no va tan rápido el video
=> Mejorar la animación en el componente de combate según el número de combate para hacer que venga de izquierda, derecha o abajo

src/components/BoxerSocialLink.astro
se tuvo que reducir el tamaño de el componente BoxerSocialLink a w-18 en tamaños de pantalla pequeños para que quede mejor el responsive.
Antes:
Despues:
=> Mejorar responsive en pagina luchador

astro.config.mjs, src/components/BoxerCard.astro, src/components/BoxerGallery.astro, src/components/Boxers/BoxerBigImages.astro, src/components/Boxers/ColumnBoxers.astro, src/components/Boxers/SelectYourBoxer.astro, src/components/Icons/HorizontalScroll.astro, src/sections/Hero.astro, src/styles/global.css
If it is a mobile device change the selector to a scrollable one, where if it clicks it adds `data-selected` first, and if clicked on a selected one, it goes to boxer's page.
https://github.com/user-attachments/assets/1b28d09a-1232-44c1-ba3e-d05d63bb665b
=> Feat: Fix responsive on boxer selection

src/components/LiteYouTube.astro, src/sections/Entradas.astro
Fix blurred image sizes
Before:
After:
=> fix: correct blurred images size to not overflow

src/styles/global.css
In mobile, some browsers have buttons at top and or at bottom of the screen, covering up some parts of the UI.
I made the change in the `global.css` because changing it in all instances and keeping track of all new uses `h-screen` or `min-h-screen` to be `h-svh md:h-screen` is not feasible with this much developers and changes.
Before:
After:
=> feat(global.css): change `h-screen` and `min-h-screen` to be dynamic

src/sections/Header.astro
Actualmente, el "nav" tiene una altura de 100vh debido a una sobreescrita por estilos globales, que en version escritorio genera una zona invisible que se superpone al contenido e impide hacer clic en elementos
Isuue abierto por @GFrancV  -> [Ver issue](https://github.com/midudev/la-velada-web-oficial/issues/1381)
https://github.com/user-attachments/assets/2d89402b-4ce5-40f5-b37c-9ba5bcdb93c9
Clase utilitaria ignorada del navbar
=> 🐛 Fix: Área invisible del <nav> bloqueando interacciones en escritorio

src/pages/luchador/[id].astro
Existía un error al hacer hover a las cards `getStaticPaths()` function required for dynamic routes., esto lo producía el estado de la constante PRERENDER en 'true' en el archivo [id].astro. está lento por que mi computador es muy básico.
##BEFORE
[erorr al hacer hover.webm](https://github.com/user-attachments/assets/77892d50-326d-47b7-8c6b-dcfa073aedda)
##AFTER
[error corregido.webm](https://github.com/user-attachments/assets/2fbb5ce6-ad74-48e9-8d93-d45af59b6ffa)
Se corrigió cambiándo el estado de la constante PRERENDER a false.
=> change state of PRERENDER to false

src/components/BoxerClipCard.astro, src/components/BoxerClipList.astro
Replaced pointers for default cursor on non-interactable texts.
Before:
After:
=> fix: accessibility by ensuring proper cursor styles on text elements

src/sections/Footer.astro
Wrapped footer's Infojobs logo in a hyperlink for external navigation.
=> fix: missing hyperlink to infojobs

src/sections/Header.astro
Se cambió el height de `#navContent` y `#overlay-menu` en mobile, de `h-screen` a `h-[100vh]`.
La razón principal es que `h-screen` aplica `height: 100svh` en CSS, a pesar de que la documentación de Tailwind CSS indica que aplica `height: 100vh`, que es lo deseado para evitar que se corte en navegadores con vh dinámico, en este caso, testeado en Brave Mobile.
[Height - Tailwind CSS](https://tailwindcss.com/docs/height)
Base:
Al hacer scroll
Antes:
Ahora:
=> Fix nav content (menu) mobile height

src/pages/404.astro
Se agregan las clases `w-fit` y `mx-auto` al elemento `span` con el texto 404 para evitar que se sobre ponga a los textos debajo de el.
El elemento `span` con el texto 404 se sobre ponía en la mitad a los textos "¡FUERA DE COMBATE!" y "vaya, parece que te han noqueado..." lo que impedía una correcta selección.
El problema radicaba en que el elemento tenia un display block lo que le daba un width: 100% y al rotarse 113 grados se sobre ponía a los otros textos, teniendo en cuenta que este elemento va primero en el DOM.
https://github.com/user-attachments/assets/efca3d39-2499-45f8-92f9-44f606198ef3
https://github.com/user-attachments/assets/5f4dda58-c22e-4d36-8329-cac2d5dd0977
=> fix: enable text selection on 404 page

src/pages/combates/index.astro, src/sections/PorraHome.astro
Se ajustó la posición de los luchadores en los combates **Viruzz vs Tomás** y **Perxitaa vs Gaspi** para evitar que se superpongan visualmente.
| Antes | Después |
|-------|---------|
| ![Antes](https://github.com/user-attachments/assets/d9b13fff-376b-477f-9d03-ecb1bef3ebc3) | ![Después](https://github.com/user-attachments/assets/1b0e3ea2-51cf-4e40-825b-b020ae721e7f) |
| ![Antes](https://github.com/user-attachments/assets/441ebced-02df-4711-bd10-cc6d8cce5f6c) | ![Después](https://github.com/user-attachments/assets/45532b3b-4586-46d2-9c23-3b0efb25ad5a) |
=> fix: ajustar separación en combates Viruzz/Tomás y Perxitaa/Gaspi

src/components/BoxerGallery.astro
Se agrega la declaracion `user-select: none` con la clase de tailwind `select-none` a los botones de next y prev para evitar que se seleccionen las imagenes de la galería al navegar rápidamente o hacer doble click en los botones.
Antes:
https://github.com/user-attachments/assets/d4fbf58c-16d2-4787-b951-7362a14284a1
Después:
https://github.com/user-attachments/assets/ab443a1b-7604-40fc-9f42-7c93050dd922
=> fix(boxer-gallery): incorrect images selection on rapid navigation clicks

src/layouts/Layout.astro, src/styles/global.css
- Se agrega la declaración `scrollbar-gutter: stable` al elemento `html` y se le establece el mismo color del `scrollbar-track` al `background-color` para que el `scrollbar-gutter` sea consistente.
- Se modifica la declaración `height: 100%` aplicada en los elementos `html` y `body` para que sea `min-height: 100%` y no limite el alto de los elementos, evitando que se corten los colores de fondo.
- Por último, se mueven los estilos globales de `Layout.astro` al archivo `globals.css` para mantener consistencia (sé que no es parte de la PR, pero me picaron las manos 😔).
Se bajó la opacidad del `backdrop` para mejorar la visualización, no es parte de la PR
Antes:
https://github.com/user-attachments/assets/ef6e72fc-cf46-4604-88f7-e24005396ea3
Después: …
=> fix(ui): prevent layout shift when opening modals using scrollbar-gutter
